---
title: "Pediatric Heart Status Exceptions"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(knitr)
opts_chunk$set(comment = NA, prompt = FALSE, cache = FALSE, echo = TRUE,
                      results = "asis")

library(tidyverse)
library(haven)
library(rmdformats)
library(dplyr)
library(tidyr)
library(lubridate)
library(gtsummary)
library(cowplot)
library(survival)
library(survminer)
library(ggsurvfit)
library(cmprsk)
library(tidycmprsk)
library(pROC)
library(risksetROC)
library(rsample)
library(sjPlot)
library(coxme)

```

```{r color_schemes}
custom_colors <- c(
  `dark red` = "#660000",
  `bright red` = "#b81d2e",
  `orange` = "#ae6320",
  `yellow`= "#b8a370",
  `green` = "#3ba9a9",
  `white` = "#FFFFFF",
  `grey` = "#C3C1C1",
  `light green` = "#8dd9d7",
  `light yellow` = "#ddd3bb",
  `light orange` = "#e49f62",
  `space sparkle`= "#496061",
  `violet` = "#7A3DE3",
  `sandy brown` = "#FA9E4D")
custom_col <- function(...) {
  cols <- c(...)
  if (is.null(cols))
    return (drsimonj_colors)
  custom_colors[cols]
}
custom_palettes <- list(
  `main`  = custom_col("green", "yellow", "dark red"),
  `cool`  = custom_col("green", "yellow","orange"),
  `hot`   = custom_col("yellow", "dark red", "sandy brown"),
  `simple` = custom_col("yellow", "dark red"),
  `reallysimple` = custom_col("white", "#00a1d5"),
  `mixed` = custom_col("green", "yellow", "orange", "bright red", "dark red"),
  `distinct` = custom_col("dark red", "bright red", "light yellow", "green","grey"),
  `distinct1` = custom_col("dark red", "bright red",  "green","light yellow","grey"), 
  `bar` = custom_col("green", "grey", "yellow", "orange", "bright red", "dark red"),
  `treatment` = custom_col("dark red","green", "space sparkle", "orange", "violet","yellow","sandy brown","bright red"),
  `exception` = custom_col("dark red", "yellow"),
  `agegroup` = custom_col("bright red", "orange", "yellow", "grey")
)
custom_pal <- function(palette = "main", reverse = FALSE, ...) {
  pal <- custom_palettes[[palette]]
  if (reverse) pal <- rev(pal)
  colorRampPalette(pal, ...)
}
scale_color_custom <- function(palette = "mixed", discrete = TRUE, reverse = FALSE, ...) {
  pal <- custom_pal(palette = palette, reverse = reverse)
  if (discrete) {
    discrete_scale("colour", paste0("custom_", palette), palette = pal, ...)
  } else {
    scale_color_gradientn(colours = pal(256), ...)
  }
}
scale_fill_custom <- function(palette = "mixed", discrete = TRUE, reverse = FALSE, ...) {
  pal <- custom_pal(palette = palette, reverse = reverse)
  if (discrete) {
    discrete_scale("fill", paste0("custom_", palette), palette = pal, ...)
  } else {
    scale_fill_gradientn(colours = pal(256), ...)
  }
}

```


``` {r load datasets}

thoracic_followup_data_2025q2 = read_sas("~/Desktop/R Project Data/HRStatJust2509DanielAhn/thoracic_followup_data_2025q2", NULL)

thoracic_data_2025q2 = read_sas("~/Desktop/R Project Data/HRStatJust2509DanielAhn/thoracic_data_2025q2", NULL)

thoracic_stat1a = read_sas("~/Desktop/R Project Data/HRStatJust2509DanielAhn/thoracic_stat1a", NULL)

thoracic_stat1b = read_sas("~/Desktop/R Project Data/HRStatJust2509DanielAhn/thoracic_stat1b", NULL)


```




# Filter and pivot data by relevant dates




``` {r data cleaning}


tx_list <- thoracic_followup_data_2025q2 %>% select(TRR_ID_CODE, PT_CODE, PX_STAT, PX_STAT_DATE) %>% 
  group_by(TRR_ID_CODE) %>% filter(PX_STAT == "A" | PX_STAT == "D" | PX_STAT == "R") %>% arrange(PX_STAT_DATE) %>%
  filter(row_number() == n())


cand_list = thoracic_data_2025q2 %>% select(PT_CODE, WL_ID_CODE, TRR_ID_CODE, INIT_DATE, INIT_STAT, COMPOSITE_DEATH_DATE, INIT_AGE, WL_ORG, END_DATE, REM_CD, LISTING_CTR_CODE, END_STAT, GENDER, ABO, THORACIC_DGN, TCR_DGN, ETHNICITY, ETHCAT, BMI_TCR, BMI_CALC, ECMO_TCR, IABP_TCR, INOTROPES_TCR, VAD_DEVICE_TY_TCR, VENTILATOR_TCR, INIT_WGT_KG_CALC, REGION) %>% 
  filter(INIT_AGE < 18) %>% filter(WL_ORG == "HR") %>% 
  filter(INIT_DATE >= mdy("03-22-2016") & INIT_DATE <= mdy("03-31-2025")) %>%
  mutate(
    period = case_when(
      INIT_DATE >= mdy("07-01-2017") & INIT_DATE <= mdy("03-31-2021") ~ "pre-nhrb",
      INIT_DATE >= mdy("07-01-2021") & INIT_DATE <= mdy("03-31-2025") ~ "post-nhrb",
      TRUE ~ "other"),
    initial_status = case_when(
      grepl("2010", INIT_STAT) ~ "1A",
      grepl("2020", INIT_STAT) ~ "1B",
      grepl("2030", INIT_STAT) ~ "2",
      grepl("2999", INIT_STAT) ~ "Inactive"),
    TX_DATE = ifelse(REM_CD == 4, END_DATE, NA),
    TX_DATE = as.Date(TX_DATE, origin = "1970-01-01")) %>% filter(initial_status != "Inactive")  


#split data into single and multiple registrations
single_registrations = cand_list %>% 
  group_by(PT_CODE) %>%
  filter(n() == 1)

multiple_registrations = cand_list %>%
  group_by(PT_CODE) %>%
  filter(n() > 1)


#distinguish type of multiple registration (concurrents must be collapsed into single listing)
multiple_registrations = multiple_registrations %>% arrange(INIT_DATE) %>%
  mutate(list_type = case_when(
    INIT_DATE < dplyr::lag(END_DATE) ~ "concurrent",
    END_DATE > dplyr::lead(INIT_DATE) ~ "concurrent",
    TRUE ~ "sequential")) 

multiple_registrations = multiple_registrations[order(multiple_registrations$PT_CODE, multiple_registrations$END_DATE), ]

 
multiple_registrations$transplant_num <- 1 
for (i in 2:nrow(multiple_registrations)) {
  if (!is.na(multiple_registrations$PT_CODE[i-1]) && 
      !is.na(multiple_registrations$PT_CODE[i]) && 
      !is.na(multiple_registrations$TX_DATE[i-1]) && 
      !is.na(multiple_registrations$TX_DATE[i]) &&
      multiple_registrations$PT_CODE[i-1] == multiple_registrations$PT_CODE[i] &&
      multiple_registrations$TX_DATE[i-1] != multiple_registrations$TX_DATE[i]) {
    
    multiple_registrations$transplant_num[i] = multiple_registrations$transplant_num[i-1] + 1
  }
}

for (i in 2:nrow(multiple_registrations)) {
  if (!is.na(multiple_registrations$PT_CODE[i-1]) && 
      !is.na(multiple_registrations$PT_CODE[i]) && 
      multiple_registrations$PT_CODE[i-1] == multiple_registrations$PT_CODE[i] &&
      !is.na(multiple_registrations$transplant_num[i-1]) && 
      multiple_registrations$transplant_num[i-1] != multiple_registrations$transplant_num[i] &&
      multiple_registrations$transplant_num[i-1] != 1) {
    
    multiple_registrations$transplant_num[i] = multiple_registrations$transplant_num[i-1]
  }
}

multiple_registrations$transplant_num[multiple_registrations$list_type == 'sequential'] <- 0 

for(i in 1:(nrow(multiple_registrations)-1)) { 
  if(multiple_registrations$PT_CODE[i] == multiple_registrations$PT_CODE[i+1] &
     multiple_registrations$list_type[i] == 'concurrent' & multiple_registrations$list_type[i+1] == 'concurrent' &
     !is.na(multiple_registrations$TX_DATE[i]) & !is.na(multiple_registrations$TX_DATE[i+1]) &
     multiple_registrations$TX_DATE[i] < multiple_registrations$TX_DATE[i+1] ) {
    
    multiple_registrations$TX_DATE[i] <- multiple_registrations$TX_DATE[i+1] ##if PERS_ID is the same as the NEXT row, both have concurrent listings, transplant dates for both are not NA, and transplant date is earlier than the next row's transplant date - update to next row's transplant date
  }}


sequential_lists <- multiple_registrations %>%
  filter(list_type == "sequential") %>%
  mutate(min_list_date = INIT_DATE)  

multiple_registrations <- multiple_registrations %>% 
  group_by(PT_CODE, transplant_num) %>%
  mutate(min_list_date = min(INIT_DATE, na.rm=T))

multiple_registrations <- multiple_registrations %>% mutate
max_retransplants <- max(multiple_registrations$transplant_num) 

collapsed_concurrent_registrations <- NULL 
for(i in 1:max_retransplants) {
  collapsed_concurrent_registrations <- rbind(collapsed_concurrent_registrations, 
        
  multiple_registrations %>%
    filter(list_type == "concurrent" & transplant_num == i) %>% 
    mutate(last_wait_date = max(END_DATE, na.rm = TRUE)) %>% 
    fill(TX_DATE, .direction = "up") %>%
    fill(REM_CD, .direction = "up") %>%
    select(-c(END_DATE, INIT_DATE)) %>%
    filter(row_number() == 1) %>%  
    mutate(last_wait_date = case_when(
      TX_DATE < last_wait_date ~ TX_DATE,
      TRUE ~ last_wait_date)))}

##recombine separated data frames

#recombined data
cand_list <- bind_rows(single_registrations %>% ungroup(), 
                       sequential_lists %>% ungroup(), 
                       collapsed_concurrent_registrations %>% ungroup()) 



#fix listing date 
cand_list = cand_list %>% 
  mutate(
    min_list_date = if_else(is.na(min_list_date), as.Date(INIT_DATE), as.Date(min_list_date)))


cand_list = cand_list %>% 
  mutate(INIT_DATE = ifelse(is.na(INIT_DATE), min_list_date, INIT_DATE),
         END_DATE = ifelse(is.na(END_DATE), last_wait_date, END_DATE),
         INIT_DATE = as.Date(INIT_DATE, origin = "1970-01-01"),
         END_DATE = as.Date(END_DATE, origin = "1970-01-01")) %>%
  select(-list_type, -transplant_num, -min_list_date, -last_wait_date)


status1ajustifications = thoracic_stat1a %>% 
  mutate(RequestedCandStatCd = 2010,
         EXCEPTION = REQ6_CRITERIA_NOT_MET,
         STATUS_JUST = case_when(
           REQ1_CONTINUOUS_VENTILATION == 1 ~ "Mechanical Ventilation",
           REQ3_DUCTAL_DEPENDENCY == 1 ~ "Ductal-Dependent Circulation",
           REQ4_CHD_DIAGNOSIS == 1 ~ "Congenital Heart Disease",
           REQ5_CIRCULATORY_DEVICE == 1 | REQ2_BALLOONPUMP == 1 ~ "MCS/IABP",
           REQ6_CRITERIA_NOT_MET == 1 ~ "1A Exception"
         )) %>% select(WL_ID_CODE, EXCEPTION, UPGRADE_EXTDATE, RequestedCandStatCd, STATUS_JUST) 

status1bjustifications = thoracic_stat1b %>% 
  mutate(RequestedCandStatCd = 2020,
         EXCEPTION = REQ3_CRITERIA_NOT_MET,
         STATUS_JUST = case_when(
           REQ2_CARDIOMYOPATHY == 1 | REQ1_INOTROPIC_AGENT == 1 ~ "Standard 1B Listing",
           REQ3_CRITERIA_NOT_MET == 1 ~ "1B Exception"
         )) %>% select(WL_ID_CODE, EXCEPTION, UPGRADE_EXTDATE, RequestedCandStatCd, STATUS_JUST) 


status_exception_justifications = rbind(status1ajustifications, status1bjustifications)


cand_hx_list = cand_list %>%
  left_join(thoracic_wlhistory_data_2025q2 %>% select(WL_ID_CODE, CHG_DATE, CHG_TY, UNOS_CAND_STAT_CD), by = "WL_ID_CODE") %>%
  group_by(WL_ID_CODE) %>% arrange(WL_ID_CODE, CHG_DATE) %>%
  mutate(
    STATUS = case_when(
      grepl("2010", UNOS_CAND_STAT_CD) ~ "1A",
      grepl("2020", UNOS_CAND_STAT_CD) ~ "1B",
      grepl("2030", UNOS_CAND_STAT_CD) ~ "2",
      grepl("2999", UNOS_CAND_STAT_CD) ~ "Inactive")) %>%
  filter(row_number() > 1) %>% distinct(WL_ID_CODE, CHG_DATE, .keep_all = TRUE) 
   




cand_hx_list_episodes = cand_hx_list %>% left_join(status_exception_justifications, by = "WL_ID_CODE") %>%
  mutate(
    matching = ifelse(UNOS_CAND_STAT_CD == RequestedCandStatCd & CHG_DATE == UPGRADE_EXTDATE, 1, 0),
    matching = ifelse(is.na(matching), 0, matching))

cand_hx_list_episodes1 = cand_hx_list_episodes %>% group_by(WL_ID_CODE, CHG_DATE) %>% arrange(CHG_DATE) %>%
  filter(matching == 1)

cand_hx_list_episodes2 = cand_hx_list_episodes %>% group_by(WL_ID_CODE, CHG_DATE) %>% arrange(CHG_DATE) %>%
  filter(matching == 0) %>% slice(1)


cand_hx_list_episodes = rbind(cand_hx_list_episodes1, cand_hx_list_episodes2) %>% ungroup() %>%
  mutate(
    UPGRADE_EXTDATE = ifelse(matching == 0, NA, UPGRADE_EXTDATE),
    UPGRADE_EXTDATE = as.Date(UPGRADE_EXTDATE, origin = "1970-01-01"),
    STATUS_JUST = ifelse(matching == 0, NA, STATUS_JUST),
    RequestedCandStatCd = ifelse(matching == 0, NA, RequestedCandStatCd),
    EXCEPTION = ifelse(matching == 0, NA, EXCEPTION)) %>% distinct()

duplicated_rows_1 <- cand_hx_list_episodes %>%
  group_by(WL_ID_CODE, CHG_DATE) %>%
  filter(n() == 1) %>% arrange(CHG_DATE) %>% ungroup()

duplicated_rows_2 <- cand_hx_list_episodes %>%
  group_by(WL_ID_CODE, CHG_DATE) %>%
  filter(n() == 2) %>% arrange(CHG_DATE) %>% filter(matching == 1) %>% ungroup()

duplicated_rows_3 <- cand_hx_list_episodes %>%
  group_by(WL_ID_CODE, CHG_DATE) %>%
  filter(n() > 2) %>% arrange(CHG_DATE) %>% filter(CHG_TY != "D") %>% 
  filter(matching == 1) %>% arrange(UNOS_CAND_STAT_CD) %>% 
  mutate(
    has_exc = case_when(
      any(EXCEPTION == 1) ~ 1,
      TRUE ~ 0))

duplicated_rows_3.1 = duplicated_rows_3 %>% filter(has_exc == 1) %>% filter(EXCEPTION == 1) %>% 
  select(-has_exc) %>% ungroup()

duplicated_rows_3.2 = duplicated_rows_3 %>% filter(has_exc == 0) %>% arrange(UNOS_CAND_STAT_CD) %>% 
  slice(1) %>% select(-has_exc) %>% ungroup()
  
cand_hx_list_episodes = rbind(duplicated_rows_1, duplicated_rows_2, duplicated_rows_3.1, duplicated_rows_3.2) %>% 
  group_by(WL_ID_CODE) %>% arrange(WL_ID_CODE, CHG_DATE) %>% filter(CHG_TY != "D") %>%
  mutate(
    index_of_exception = which(EXCEPTION == 1) [1],
    CHG_END_DATE = dplyr::lead(CHG_DATE),
    CHG_END_DATE = ifelse(is.na(CHG_END_DATE), END_DATE, CHG_END_DATE),
    CHG_END_DATE = as.Date(CHG_END_DATE, origin = "1970-01-01"),
    start = as.numeric(difftime(CHG_DATE, INIT_DATE, units = "days")),
    end = as.numeric(difftime(CHG_END_DATE, INIT_DATE, units = "days")),
    EXCEPTION = ifelse(is.na(EXCEPTION), 0, EXCEPTION)) %>%
  filter(!(row_number() == n() & last(CHG_END_DATE) %in% head(CHG_END_DATE, -1))) %>%
  filter(CHG_END_DATE > CHG_DATE) %>%
  mutate(
    is_last_row = row_number() == n(),
    death = case_when(
      is_last_row == TRUE & (REM_CD == 8 | REM_CD == 13) ~ 1,
      TRUE ~ 0),
    transplant = case_when(
      is_last_row == TRUE & REM_CD == 4 ~ 1,
      TRUE ~ 0),
    death = ifelse(is.na(death), 0, death),
    transplant = ifelse(is.na(transplant), 0, transplant)) 


cand_hx_list_episodes_grouping = cand_hx_list_episodes %>% 
  group_by(grp = cumsum(EXCEPTION == 1)) %>% 
  mutate(numbering = row_number()) %>%
  mutate(
    time_since_exception = as.numeric(difftime(CHG_DATE, first(CHG_DATE), units = "days")),
    new_fill_for_exception = case_when(
      grp > 0 & first(STATUS) == "1A" & UNOS_CAND_STAT_CD == first(UNOS_CAND_STAT_CD) & time_since_exception <= 14 & WL_ID_CODE == first(WL_ID_CODE) ~ 1,
      grp > 0 & first(STATUS) == "1B" & UNOS_CAND_STAT_CD == first(UNOS_CAND_STAT_CD) & WL_ID_CODE == first(WL_ID_CODE) ~ 1,
      TRUE ~ 0),
    EXCEPTION = ifelse(new_fill_for_exception == 1, 1, EXCEPTION))


cand_hx_list_episodes_grouping = cand_hx_list_episodes_grouping %>%
  mutate(EXCEPTION = ifelse(STATUS == "Inactive", NA, EXCEPTION)) %>%
  mutate(STATUS = factor(case_when(
    !(UNOS_CAND_STAT_CD %in% c(1999, 2999)) ~ STATUS))) %>%
  group_by(WL_ID_CODE) %>%
  fill(STATUS, .direction = "down") %>%
  fill(EXCEPTION, .direction = "down") %>%
  fill(STATUS_JUST, .direction = "down") %>%
  ungroup()

cand_hx_list_episodes_grouping = cand_hx_list_episodes_grouping %>%
  mutate(REC_EXCEPTION_EVER = case_when(EXCEPTION == 1 ~ 1)) %>%
  group_by(WL_ID_CODE) %>%
  fill(REC_EXCEPTION_EVER, .direction = "downup") %>%
  ungroup() %>%
  mutate(REC_EXCEPTION_EVER = tidyr::replace_na(REC_EXCEPTION_EVER, 0))

cand_hx_list_episodes_grouping <- cand_hx_list_episodes_grouping %>%
  mutate(
    REC_EXCEPTION_INIT = case_when(
      EXCEPTION == 1 & start == 0 ~ 1)) %>%
  group_by(WL_ID_CODE) %>%
  fill(REC_EXCEPTION_INIT, .direction = "downup") %>%
  ungroup() %>%
  mutate(REC_EXCEPTION_INIT = tidyr::replace_na(REC_EXCEPTION_INIT, 0))

cand_hx_list_episodes_grouping <- cand_hx_list_episodes_grouping %>%
  mutate(
    REC_EXCEPTION_INIT_EVER = factor(
      case_when(
        REC_EXCEPTION_INIT == 1 ~ "Exception at Listing",
        REC_EXCEPTION_EVER == 1 & REC_EXCEPTION_INIT == 0 ~ "Exception after Listing",
        TRUE ~ "No Exception"),
      levels = c("Exception at Listing",
                 "Exception after Listing",
                 "No Exception")))


cand_hx_list_episodes_grouping = cand_hx_list_episodes_grouping %>%
  mutate(
    STATUS = relevel(STATUS, ref = "2"),
    EXCEPTION_STATUS = factor(
      case_when(
        STATUS == "1A" &
          EXCEPTION == 0 ~ "Status 1A No Exception",
        STATUS == "1A" &
          EXCEPTION == 1 ~ "Status 1A Exception",
        STATUS == "1B" &
          EXCEPTION == 0 ~ "Status 1B No Exception",
        STATUS == "1B" &
          EXCEPTION == 1 ~ "Status 1B Exception",
        TRUE ~ "Status 2"),
      levels = c(
        "Status 1A No Exception",
        "Status 1A Exception",
        "Status 1B No Exception",
        "Status 1B Exception",
        "Status 2")),
    EXCEPTION_STATUS = relevel(EXCEPTION_STATUS, ref = "Status 2"))


cand_hx_list_episodes_grouping = cand_hx_list_episodes_grouping %>%
  ungroup() %>% group_by(WL_ID_CODE) %>% arrange(WL_ID_CODE, CHG_DATE) %>%
  mutate(
    STATUS_JUST = case_when(
      STATUS == "2" ~ "2",
      TRUE ~ STATUS_JUST)) %>%
  fill(STATUS_JUST, .direction = "down") %>%
  mutate(
    STATUS_JUST = case_when(
      STATUS_JUST == "1A Exception" ~ "Status 1A: Exception",
      STATUS_JUST == "Congenital Heart Disease" ~ "Status 1A: Congenital Heart Disease",
      STATUS_JUST == "Ductal-Dependent Circulation" ~ "Status 1A: Ductal-Dependent Circulation",
      STATUS_JUST == "MCS/IABP" ~ "Status 1A: MCS/IABP",
      STATUS_JUST == "Mechanical Ventilation" ~ "Status 1A: Mechanical Ventilation",
      STATUS_JUST == "1B Exception" ~ "Status 1B: Exception",
      STATUS_JUST == "Standard 1B Listing" ~ "Status 1B: Standard 1B Listing",
      STATUS_JUST == "2" ~ "Status 2"),
    STATUS_JUST = factor(STATUS_JUST, levels = c("Status 2", "Status 1B: Exception", "Status 1B: Standard 1B Listing", "Status 1A: Exception", "Status 1A: Congenital Heart Disease", "Status 1A: Ductal-Dependent Circulation", "Status 1A: MCS/IABP", "Status 1A: Mechanical Ventilation")))


last_observations = cand_hx_list_episodes %>% group_by(WL_ID_CODE) %>% arrange(CHG_DATE) %>% filter(row_number() == n())

```


``` {r fortable1}

fortable1 = cand_hx_list_episodes_grouping %>% group_by(WL_ID_CODE) %>% slice(1) %>%
  mutate(
    sex = ifelse(GENDER == "M", "Male", "Female"),
    sex = factor(sex, levels = c("Male", "Female")),
    race = case_when(
      ETHCAT == 1 ~ "White",
      ETHCAT == 2 ~ "Black",
      ETHCAT == 4 ~ "Hispanic/Latino",
      ETHCAT == 5 ~ "Asian",
      TRUE ~ "Other"),
    race = factor(race, levels = c("White", "Black", "Hispanic/Latino", "Asian", "Other")),
    REC_EXCEPTION_INIT_EVER = factor(REC_EXCEPTION_INIT_EVER, levels = c("No Exception", "Exception at Listing", "Exception after Listing")),
    age_group = case_when(
      INIT_AGE < 1 ~ "<1 Year",
      INIT_AGE >= 1 & INIT_AGE < 5 ~ "1-4 Years",
      INIT_AGE >= 5 & INIT_AGE < 12 ~ "5-11 Years",
      INIT_AGE >= 12 ~ ">11 Years"),
    age_group = factor(age_group, levels = c("<1 Year", "1-4 Years", "5-11 Years", ">11 Years")),
    blood_type = factor(
      case_when(
        ABO %in% c("A", "A1", "A2") ~ "A",
        ABO %in% c("A1B", "A2B") ~ "AB",
        TRUE ~ ABO)),
    blood_type_dummy = case_when(
      ABO == "O" ~ "Blood Type O",
      TRUE ~ "Non-Blood Type O"),
    blood_type_dummy = factor(blood_type_dummy, levels = c("Non-Blood Type O", "Blood Type O")),
    weight_group = case_when(
      INIT_WGT_KG_CALC < 25 ~ "Less than 25 kg",
      TRUE ~ "25 kg or Greater"),
    weight_group = factor(weight_group, levels = c("25 kg or Greater", "Less than 25 kg")),
    diagnosis = case_when(
      TCR_DGN > 999 & TCR_DGN < 1007 ~ "Dilated Cardiomyopathy, Non-Ischemic",
      TCR_DGN > 1049 & TCR_DGN < 1100 ~ "Restrictive Cardiomyopathy",
      TCR_DGN == 1203 | (TCR_DGN >= 1205 & TCR_DGN <= 1207) ~ "Congenital Heart Disease",
      TCR_DGN == 1201 ~ "Hypertrophic Cardiomyopathy",
      TCR_DGN >= 1100 & TCR_DGN <= 1199 ~ "Re-Heart Transplant",
      TRUE ~ "Other"),
    diagnosis = factor(diagnosis, levels = c("Dilated Cardiomyopathy, Non-Ischemic", "Restrictive Cardiomyopathy", 
                                             "Congenital Heart Disease", "Hypertrophic Cardiomyopathy", 
                                             "Re-Heart Transplant", "Other")),
    diagnosis_dummy = case_when(
      diagnosis == "Dilated Cardiomyopathy, Non-Ischemic" ~ "Dilated Cardiomyopathy",
      diagnosis == "Congenital Heart Disease" ~ "Congenital Heart Disease",
      diagnosis == "Re-Heart Transplant" ~ "Re-Heart Transplant",
      TRUE ~ "Other"),
    diagnosis_dummy = factor(diagnosis_dummy, levels = c("Dilated Cardiomyopathy", "Congenital Heart Disease", "Re-Heart Transplant", "Other")),
    inotropes = ifelse(INOTROPES_TCR == 1, "IV Inotropes", "None"),
    ECMO = ifelse(ECMO_TCR == 1, "ECMO", "None"),
    IABP = ifelse(IABP_TCR == 1, "IABP", "None"),
    ventilation = ifelse(VENTILATOR_TCR == 1, "Mechanical Ventilation", "None"),
    VAD = ifelse(VAD_DEVICE_TY_TCR == 2 | VAD_DEVICE_TY_TCR == 3 | VAD_DEVICE_TY_TCR == 5, "VAD", "None"))

var_label_list <- list(age_group = "Age at Listing",
                       sex = "Sex",
                       race = "Race",
                       INIT_WGT_KG_CALC = "Weight (Kilograms)",
                       initial_status = "Status at Initial Listing",
                       blood_type = "Blood Type",
                       diagnosis = "Primary Diagnosis",
                       REC_EXCEPTION_INIT_EVER = "Exception Status",
                       VAD = "VAD at Initial Listing",
                       inotropes = "IV Inotropes at Initial Listing",
                       ECMO = "ECMO at Initial Listing",
                       IABP = "IABP at Initial Listing",
                       ventilation = "Mechanical Ventilation at Initial Listing")
labelled::var_label(fortable1) <- var_label_list


fortable1 %>% ungroup() %>%
  dplyr::select(
    age_group, sex, race, INIT_WGT_KG_CALC, blood_type, diagnosis, initial_status, REC_EXCEPTION_INIT_EVER) %>%
  tbl_summary(by = REC_EXCEPTION_INIT_EVER, digits = list(all_categorical() ~ c(0, 1))) %>%
  add_p(test.args = all_tests("chisq.test") ~ list(workspace=2e7)) %>%
  add_overall() %>% 
  #remove_row_type(variables = c(pcwp, cardiac_index), type = "missing", level_value = ("(Missing)")) %>%
  remove_row_type(variables = c(INIT_WGT_KG_CALC), type = "missing", level_value = ("(Unknown)")) %>%
  as_gt()




number <- fortable1 %>% group_by(LISTING_CTR_CODE) %>%
  summarise(n = n())

fortable1 <- fortable1 %>% left_join(number) %>% ungroup() %>% group_by(LISTING_CTR_CODE) %>% arrange(n, LISTING_CTR_CODE)
  
groups = fortable1$LISTING_CTR_CODE %>% unique
i = 0
fortable1$center = NA
for (g in groups) {
  i = i + 1
  fortable1[fortable1$LISTING_CTR_CODE == g, ]$center = i
}

rates <- fortable1 %>% ungroup() %>% group_by(LISTING_CTR_CODE) %>%
  summarize(
    prop_applied_exceptions = sum(REC_EXCEPTION_EVER == 1) / n(),
    number_exceptions = sum(REC_EXCEPTION_EVER == 1),
    prop_exceptions_whole = sum(REC_EXCEPTION_EVER == 1) / 6026) %>%
  arrange(-number_exceptions) %>%
  mutate(Cum = cumsum(number_exceptions)) %>%
  mutate(CumProp = cumsum(prop_exceptions_whole))


median(rates$prop_applied_exceptions)


fortable1$REC_EXCEPTION_EVER <- factor(fortable1$REC_EXCEPTION_EVER,
                                       levels = c(0, 1),
                                       labels = c("Standard Criteria Listing", "Received Exception"))

```


``` {r LOGISTIC REGRESSION}

#The following code is for the construction of our mixed-effects logistric regression model. 

library(lme4)

exception_logit = glmer(REC_EXCEPTION_EVER ~ sex + race + age_group + blood_type_dummy + weight_group + diagnosis_dummy +
                          (1 | LISTING_CTR_CODE),
                        data = fortable1, family = binomial(link = "logit"))

exp(fixef(exception_logit))
exp(confint(exception_logit, method = "Wald", parm = "beta_"))

# Or get formatted table
tab_model(exception_logit, 
          show.re.var = TRUE,  # Show random effect variance
          show.icc = TRUE)      # Show ICC

labels_reversed = rev(c("Sex (Ref Male): Female",
                           "Race (Ref White): Black",
                           "Race (Ref White): Hispanic/Latino",
                           "Race (Ref White): Asian",
                           "Race (Ref White): Other",
                           "Age Group (Ref < 1 Year): 1-4 Years",
                           "Age Group (Ref < 1 Year): 5-11 Years",
                           "Age Group (Ref < 1 Year): >11 Years",
                           "Blood Type (Ref Non-O): O",
                           "Weight Group (Ref 25 kg or More): <25 kg",
                           "Dignosis (Ref DCM): CHD",
                           "Dignosis (Ref DCM): Re-Transplant",
                           "Dignosis (Ref DCM): Other"))

plot_model(exception_logit, 
           show.values = TRUE,
           value.offset = 0.3,
           value.size = 6,
           order.terms = c(1:13),
           axis.lim = c(0.5, 10),
           grid.breaks = c(0.5, 1, 5, 10),
           axis.labels = labels_reversed,
           title = "Odds Ratios for Exception Receipt") +
  theme_classic() +
  theme(text = element_text(size = 18),
        axis.text.x = element_text(size = 16),
        axis.title.x = element_text(size = 18),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)) +
  geom_hline(yintercept = 1, linetype = "dotted", linewidth = 1, color = "black")



library(lme4)
library(DHARMa)
library(car)
library(dplyr)

exception_logit <- glmer(REC_EXCEPTION_EVER ~ sex + race + age_group + 
                          blood_type_dummy + weight_group + diagnosis_dummy +
                          (1 | LISTING_CTR_CODE),
                        data = fortable1, 
                        family = binomial(link = "logit"),
                        control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))


#The following code is for model assumptions testing


# ===== 1. CHECK OVERALL MODEL FIT =====
# DHARMa residuals
sim_resid <- simulateResiduals(exception_logit, n = 1000)
plot(sim_resid)  # QQ plot and residuals vs predicted
# p > 0.05 = good fit

testDispersion(sim_resid)  # Should be > 0.05
testOutliers(sim_resid)    # Should be > 0.05

testCategorical(sim_resid, catPred = fortable1$sex)
testCategorical(sim_resid, catPred = fortable1$race)
testCategorical(sim_resid, catPred = fortable1$age_group)


sens_exception_logit <- glmer(REC_EXCEPTION_EVER ~ sex + race + age_group + blood_type_dummy + weight_group + diagnosis_dummy + age_group * diagnosis_dummy + (1 | LISTING_CTR_CODE), data = fortable1, family = binomial(link = "logit"), control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))


labels_reversed = rev(c("Sex (Ref Male): Female",
                        "Race (Ref White): Black",
                        "Race (Ref White): Hispanic/Latino",
                        "Race (Ref White): Asian",
                        "Race (Ref White): Other",
                        "Age Group (Ref < 1 Year): 1-4 Years",
                        "Age Group (Ref < 1 Year): 5-11 Years",
                        "Age Group (Ref < 1 Year): >11 Years",
                        "Blood Type (Ref Non-O): O",
                        "Weight Group (Ref 25 kg or More): <25 kg",
                        "Diagnosis (Ref DCM): CHD",
                        "Diagnosis (Ref DCM): Re-Transplant",
                        "Diagnosis (Ref DCM): Other",
                        "Dx * Age (Ref DCM & <1 Year): CHD & 1-4 Years",
                        "Dx * Age (Ref DCM & <1 Year): CHD & 5-11 Years",
                        "Dx * Age (Ref DCM & <1 Year): CHD & >11 Years",
                        "Dx * Age (Ref DCM & <1 Year): Re-HT & 1-4 Years",
                        "Dx * Age (Ref DCM & <1 Year): Re-HT & 5-11 Years",
                        "Dx * Age (Ref DCM & <1 Year): Re-HT & >11 Years",
                        "Dx * Age (Ref DCM & <1 Year): Other & 1-4 Years",
                        "Dx * Age (Ref DCM & <1 Year): Other & 5-11 Years",
                        "Dx * Age (Ref DCM & <1 Year): Other & >11 Years"))

sensitivity_logit = plot_model(sens_exception_logit, 
           show.values = TRUE,
           value.offset = 0.3,
           value.size = 6,
           order.terms = c(1:22),
           axis.lim = c(0.01, 1000),
           grid.breaks = c(0.01, 0.1, 1, 5, 10, 100, 1000),
           axis.labels = labels_reversed,
           title = "") +
  theme_classic() +
  theme(text = element_text(size = 18),
        axis.text.x = element_text(size = 16),
        axis.title.x = element_text(size = 18),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 18),
        legend.text = element_text(size = 18),
        legend.title = element_text(size = 18)) +
  geom_hline(yintercept = 1, linetype = "dotted", linewidth = 1, color = "black")



library(performance)
compare_performance(exception_logit, sens_exception_logit)

summary(sens_exception_logit)


exp(fixef(sens_exception_logit))
exp(confint(sens_exception_logit, method = "Wald", parm = "beta_"))



# ===== 2. CHECK NORMALITY OF RANDOM EFFECTS =====
ranef_values <- ranef(exception_logit)$LISTING_CTR_CODE[,1]

# QQ plot
qqnorm(ranef_values, main = "Q-Q Plot of Center Random Effects")
qqline(ranef_values, col = "red")

# Shapiro-Wilk test
shapiro.test(ranef_values)  # p > 0.05 = normal

# Histogram
hist(ranef_values, breaks = 20,
     main = "Distribution of Center Random Effects",
     xlab = "Random Effect")


# ===== 4. CHECK MULTICOLLINEARITY =====
# Fit without random effects first
logit_no_re <- glm(REC_EXCEPTION_EVER ~ sex + race + age_group + 
                    blood_type_dummy + weight_group + diagnosis_dummy,
                   data = fortable1, 
                   family = binomial)

vif_values <- vif(logit_no_re)
print("VIF values:")
print(vif_values)
# VIF < 5 = good

# ===== 5. CHECK CLUSTER SIZE ADEQUACY =====
cluster_summary <- fortable1 %>% ungroup() %>%
  group_by(LISTING_CTR_CODE) %>%
  summarise(
    n_patients = n(),
    n_exceptions = sum(REC_EXCEPTION_EVER == "Received Exception"),
    exception_rate = mean(REC_EXCEPTION_EVER == "Received Exception")
  ) %>%
  arrange(n_patients)

print(summary(cluster_summary))

# Count small clusters
small_clusters <- cluster_summary %>%
  filter(n_patients < 10 | n_exceptions < 5)
print(paste0("Small clusters: ", nrow(small_clusters), " out of ", 
             nrow(cluster_summary)))

# ===== 6. SENSITIVITY ANALYSIS - EXCLUDE SMALL CENTERS =====
adequate_centers <- cluster_summary %>%
  filter(n_patients >= 10, n_exceptions >= 5) %>%
  pull(LISTING_CTR_CODE)

print(paste0("Adequate centers: ", length(adequate_centers), 
             " out of ", nrow(cluster_summary)))

# Refit model
fortable1_adequate <- fortable1 %>%
  filter(LISTING_CTR_CODE %in% adequate_centers)

exception_logit_sensitivity <- glmer(REC_EXCEPTION_EVER ~ sex + race + age_group + 
                                      blood_type_dummy + weight_group + diagnosis_dummy +
                                      (1 | LISTING_CTR_CODE),
                                    data = fortable1_adequate, 
                                    family = binomial(link = "logit"))

# Compare odds ratios
comparison <- data.frame(
  Variable = names(fixef(exception_logit)),
  All_Centers_OR = exp(fixef(exception_logit)),
  Adequate_Centers_OR = exp(fixef(exception_logit_sensitivity)),
  Percent_Change = (exp(fixef(exception_logit_sensitivity)) - 
                    exp(fixef(exception_logit))) / 
                   exp(fixef(exception_logit)) * 100
)

print("Odds ratio comparison:")
print(comparison)

# Compare variance of random effects
cat("\n=== Random Effect Variance ===\n")
cat("All centers:", VarCorr(exception_logit)$LISTING_CTR_CODE[1], "\n")
cat("Adequate centers:", VarCorr(exception_logit_sensitivity)$LISTING_CTR_CODE[1], "\n")

# ===== 7. CHECK FOR OVERDISPERSION =====
# Already handled by DHARMa plot
testDispersion(sim_resid)  # p > 0.05 = no overdispersion

# ===== 8. CHECK FOR OUTLIERS =====
testOutliers(sim_resid)  # p > 0.05 = no outliers


``` 

``` {r figure 4}
library(emmeans)
library(ggplot2)
library(dplyr)

#The following code is for the creation of Figure 3

# Get predicted probabilities with confidence intervals
emm <- emmeans(sens_exception_logit, ~ age_group | diagnosis_dummy, 
               type = "response")
emm_df <- as.data.frame(emm)

# Create publication-quality plot
interaction_plot = ggplot(emm_df, aes(x = age_group, y = prob, 
                   color = diagnosis_dummy, group = diagnosis_dummy)) +
  geom_point(size = 4) +
  geom_line(linewidth = 1.2) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), 
                width = 0.2, linewidth = 1) +
  scale_color_manual(name = "Diagnosis",
                     values = c("Dilated Cardiomyopathy" = "#374e55",
                               "Congenital Heart Disease" = "#df8f44",
                               "Re-Heart Transplant" = "#00a1d5",
                               "Other" = "gray60")) +
  labs(x = "Age Group", 
       y = "Predicted Probability of Exception Receipt") +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent) +
  theme_classic() +
  theme(text = element_text(size = 16),
        axis.text = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.position = "bottom")

interaction_plot



emm_pairs <- pairs(emm, by = "age_group", reverse = TRUE) # reverse to get CHD/Cardiomyopathy
summary(emm_pairs, infer = TRUE)

pairs_result <- pairs(emm, by = "age_group")  # reverse to get CHD/Cardiomyopathy
summary(pairs_result, infer = TRUE)  # infer=TRUE gives CIs



sim_resid2 <- simulateResiduals(sens_exception_logit, n = 1000)
plot(sim_resid2)

testDispersion(sim_resid2)  # Should be n.s.
testOutliers(sim_resid2)    # Should be n.s.



```



``` {r first survival model}
# cand_hx_list_episodes_grouping = cand_hx_list_episodes_grouping %>%
#   mutate(
#     EXCEPTION_STATUS = factor(EXCEPTION_STATUS, 
#                               labels = c("Status 2", "Status 1B No Exception", "Status 1B Exception",
#                                          "Status 1A No Exception", "Status 1A Exception")))
cand_hx_list_episodes_grouping = cand_hx_list_episodes_grouping %>%
  mutate(
    diagnosis = case_when(
      TCR_DGN > 999 & TCR_DGN < 1007 ~ "Dilated Cardiomyopathy, Non-Ischemic",
      TCR_DGN > 1049 & TCR_DGN < 1100 ~ "Restrictive Cardiomyopathy",
      TCR_DGN == 1203 | (TCR_DGN >= 1205 & TCR_DGN <= 1207) ~ "Congenital Heart Disease",
      TCR_DGN == 1201 ~ "Hypertrophic Cardiomyopathy",
      TCR_DGN >= 1100 & TCR_DGN <= 1199 ~ "Re-Heart Transplant",
      TRUE ~ "Other"),
    diagnosis = factor(diagnosis, levels = c("Dilated Cardiomyopathy, Non-Ischemic", "Restrictive Cardiomyopathy", 
                                             "Congenital Heart Disease", "Hypertrophic Cardiomyopathy", 
                                             "Re-Heart Transplant", "Other")),
    diagnosis_dummy = case_when(
      diagnosis == "Dilated Cardiomyopathy, Non-Ischemic" ~ "Dilated Cardiomyopathy",
      diagnosis == "Congenital Heart Disease" ~ "Congenital Heart Disease",
      diagnosis == "Re-Heart Transplant" ~ "Re-Heart Transplant",
      TRUE ~ "Other"),
    diagnosis_dummy = factor(diagnosis_dummy, levels = c("Dilated Cardiomyopathy", "Congenital Heart Disease", "Re-Heart Transplant", "Other")))



first_model_death <- coxme(Surv(start, end, death) ~ EXCEPTION_STATUS + (1 | LISTING_CTR_CODE), data = cand_hx_list_episodes_grouping)

# first_model_transplant <- coxme(Surv(start, end, transplant) ~ EXCEPTION_STATUS + (1 | LISTING_CTR_CODE), data = cand_hx_list_episodes_grouping)
    
labels_reversed = rev(c("Status 1A Exception", 
                        "Status 1A No Exception",
                        "Status 1B Exception",
                        "Status 1B No Exception"))


summary(first_model_death)

first_plot_death = plot_model(
  first_model_death,
  show.values = TRUE,
  value.offset = .3,
  axis.labels = labels_reversed,
  title = "Mixed Effects Cox Model with Center Random Effects",
  axis.title = "Hazard Ratio"
)
# 
# first_plot_transplant = plot_model(
#   first_model_transplant,
#   show.values = TRUE,
#   value.offset = .3,
#   axis.labels = c(
#     "Status 2",
#     "Status 1A Exception",
#     "Status 1A No Exception",
#     "Status 1B Exception",
#     "Status 1B No Exception"),
#   title = "Mixed Effects Model with Center Random Effects",
#   axis.title = "Hazard Ratio"
# )
    
    
```
   
   
``` {r second survival model}    
second_model_death <- coxme(Surv(start, end, death) ~ EXCEPTION + STATUS + (1 | LISTING_CTR_CODE), data = cand_hx_list_episodes_grouping)
# second_model_transplant <- coxme(Surv(start, end, transplant) ~ EXCEPTION + STATUS + (1 | LISTING_CTR_CODE), data = cand_hx_list_episodes)


summary(second_model_death)
exp(confint(second_model_death))

second_plot_death = plot_model(
  second_model_death,
  show.values = TRUE,
  value.offset = .3,
  value.size = 6,
  axis.labels = c(
    "Status (Ref 2): 1A",
    "Status (Ref 2): 1B",
    "Exception"),
  title = "",
  axis.title = "Hazard Ratio of Pre-Transplant Mortality",
  grid.breaks = c(0.1, 1, 10, 100)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(size = 18),
        axis.title.x = element_text(size = 20),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)) +
  geom_hline(yintercept = 1, linetype = "dotted", linewidth = 1, color = "black")

```

``` {r second cox model assumptions}

library(survival)
library(coxme)
library(car)
library(dplyr)


# Fit regular Cox without random effects
cox_regular <- coxph(Surv(start, end, death) ~ EXCEPTION + STATUS, 
                     data = cand_hx_list_episodes_grouping)
ph_test <- cox.zph(cox_regular)
print(ph_test)  # p > 0.05 = assumption met
plot(ph_test)   # Flat lines = good

# 2. Check normality of random effects (frailty)
frailty_values <- ranef(second_model_death)$LISTING_CTR_CODE

# QQ plot
qqnorm(frailty_values, main = "Q-Q Plot of Center Random Effects")
qqline(frailty_values, col = "red")

# Shapiro-Wilk test
shapiro.test(frailty_values)  # p > 0.05 = normal

# Histogram
hist(frailty_values, breaks = 20,
     main = "Distribution of Center Random Effects (Frailty)",
     xlab = "Random Effect")

# 3. Check multicollinearity
vif(cox_regular)  # VIF < 5 = good

# 4. Check cluster size adequacy
cluster_summary <- cand_hx_list_episodes_grouping %>%
  group_by(LISTING_CTR_CODE) %>%
  summarise(
    n_episodes = n(),
    n_deaths = sum(death),
    death_rate = mean(death)
  ) %>%
  arrange(n_episodes)

summary(cluster_summary)

# Count small clusters
small_clusters <- cluster_summary %>%
  filter(n_episodes < 10 | n_deaths < 5)
print(paste0("Number of small clusters: ", nrow(small_clusters), " out of ", 
             nrow(cluster_summary)))

# 5. Compare fixed effects between models
comparison <- data.frame(
  Variable = names(coef(cox_regular)),
  Regular_Cox = coef(cox_regular),
  Mixed_Cox = fixef(second_model_death)
)
print(comparison)



library(survival)
library(coxme)
library(dplyr)

# 1. Identify adequate centers (≥10 episodes AND ≥5 deaths)
adequate_centers <- cluster_summary %>%
  filter(n_episodes >= 10, n_deaths >= 5) %>%
  pull(LISTING_CTR_CODE)

print(paste0("Adequate centers: ", length(adequate_centers), " out of 84"))

# 2. Filter dataset to adequate centers only
cand_adequate <- cand_hx_list_episodes_grouping %>%
  filter(LISTING_CTR_CODE %in% adequate_centers)

print(paste0("Original episodes: ", nrow(cand_hx_list_episodes_grouping)))
print(paste0("Adequate center episodes: ", nrow(cand_adequate)))
print(paste0("Deaths in adequate centers: ", sum(cand_adequate$death)))

# 3. Refit model with adequate centers only
model_sensitivity <- coxme(Surv(start, end, death) ~ EXCEPTION + STATUS + 
                            (1 | LISTING_CTR_CODE), 
                           data = cand_adequate)

# 4. Compare fixed effects (hazard ratios)
comparison <- data.frame(
  Variable = names(fixef(second_model_death)),
  All_Centers_Coef = fixef(second_model_death),
  All_Centers_HR = exp(fixef(second_model_death)),
  Adequate_Centers_Coef = fixef(model_sensitivity),
  Adequate_Centers_HR = exp(fixef(model_sensitivity)),
  Percent_Change = (exp(fixef(model_sensitivity)) - exp(fixef(second_model_death))) / 
                   exp(fixef(second_model_death)) * 100
)

print(comparison)

# 5. Compare variance of random effects
cat("\n=== Random Effect Variance ===\n")
cat("All centers:", VarCorr(second_model_death)$LISTING_CTR_CODE[1], "\n")
cat("Adequate centers:", VarCorr(model_sensitivity)$LISTING_CTR_CODE[1], "\n")

# 6. Compare model summaries
cat("\n=== Full Model Summary ===\n")
print(summary(second_model_death))

cat("\n=== Sensitivity Model Summary ===\n")
print(summary(model_sensitivity))


```


``` {r third survival model}

third_model_death <- coxme(Surv(start, end, death) ~ STATUS_JUST + (1 | LISTING_CTR_CODE), data = cand_hx_list_episodes_grouping)


summary(third_model_death)
exp(confint(third_model_death))

third_plot_death = plot_model(
  third_model_death,
  show.values = TRUE,
  value.offset = .3,
  value.size = 6,
  # axis.labels = c(
  #   "Status (Ref 2): 1A",
  #   "Status (Ref 2): 1B",
  #   "Exception"),
  title = "",
  axis.title = "Hazard Ratio of Pre-Transplant Mortality",
  grid.breaks = c(0.1, 1, 10, 100)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(size = 18),
        axis.title.x = element_text(size = 20),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)) +
  geom_hline(yintercept = 1, linetype = "dotted", linewidth = 1, color = "black")





cand_hx_list_episodes_grouping$STATUS_JUST_relevel = relevel(cand_hx_list_episodes_grouping$STATUS_JUST, ref = "Status 1A: Exception")

# Fit model with new reference
cox_model_relevel = coxme(Surv(start, end, death) ~ STATUS_JUST_relevel + (1 | LISTING_CTR_CODE), data = cand_hx_list_episodes_grouping)

# Look for "Status 1A: Exception" coefficient
summary(cox_model_relevel)

# Get HR and 95% CI for "Status 1A: Exception" vs "Status 1B: Inotropic Support"
coef_summary <- summary(cox_model_relevel)$coefficients
conf_int <- summary(cox_model_relevel)$conf.int
exp(confint(cox_model_relevel))


releveled_plot_with_1a_exceptions = plot_model(
  cox_model_relevel,
  show.values = TRUE,
  value.offset = .3,
  value.size = 6,
  axis.labels = c(
    "1A: Mechanical Ventilation",
    "1A: MCS/IABP",
    "1A: Ductal-Dependent Circulation",
    "1A: Congenital Heart Disease",
    "1B: Standard Listing",
    "1B: Exception",
    "Status 2"),
  title = "",
  axis.title = "Hazard Ratio of Pre-Transplant Mortality",
  grid.breaks = c(0.1, 1, 10, 100)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(size = 18),
        axis.title.x = element_text(size = 20),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)) +
  geom_hline(yintercept = 1, linetype = "dotted", linewidth = 1, color = "black")



cand_hx_list_episodes_grouping$STATUS_JUST_relevel_again = relevel(cand_hx_list_episodes_grouping$STATUS_JUST, ref = "Status 1B: Exception")

# Fit model with new reference
cox_model_relevel_again = coxme(Surv(start, end, death) ~ STATUS_JUST_relevel_again + (1 | LISTING_CTR_CODE), data = cand_hx_list_episodes_grouping)

# Look for "Status 1A: Exception" coefficient
summary(cox_model_relevel_again)

# Get HR and 95% CI for "Status 1A: Exception" vs "Status 1B: Inotropic Support"
coef_summary <- summary(cox_model_relevel_again)$coefficients
conf_int <- summary(cox_model_relevel_again)$conf.int
exp(confint(cox_model_relevel_again))

releveled_plot_with_1b_exceptions = plot_model(
  cox_model_relevel_again,
  show.values = TRUE,
  value.offset = .3,
  value.size = 6,
  axis.labels = c(
    "1A: Mechanical Ventilation",
    "1A: MCS/IABP",
    "1A: Ductal-Dependent Circulation",
    "1A: Congenital Heart Disease",
    "1A: Exception",
    "1B: Standard Listing",
    "Status 2"),
  title = "",
  axis.title = "Hazard Ratio of Pre-Transplant Mortality",
  grid.breaks = c(0.1, 1, 10, 100)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(size = 18),
        axis.title.x = element_text(size = 20),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)) +
  geom_hline(yintercept = 1, linetype = "dotted", linewidth = 1, color = "black")


# 
# 
# summary(second_model_transplant)
# exp(confint(second_model_transplant))
# 
# second_plot_transplant = plot_model(
#   second_model_transplant,
#   show.values = TRUE,
#   value.offset = .3,
#   value.size = 6,
#   axis.labels = c(
#     "Status 1B",
#     "Status 1A",
#     "Exception"),
#   title = "",
#   axis.title = "Hazard Ratio of Pre-Transplant Mortality",
#   grid.breaks = c(0.01, 0.1, 1, 10, 100)) +
#   theme_classic() +
#   theme(text = element_text(size = 20),
#         axis.text.x = element_text(size = 18),
#         axis.title.x = element_text(size = 20),
#         axis.text.y = element_text(size = 18),
#         axis.title.y = element_text(size = 20),
#         legend.text = element_text(size = 20),
#         legend.title = element_text(size = 20))


```

``` {r fourth survival model}

fourth_model_death <- coxme(Surv(start, end, death) ~ STATUS + EXCEPTION + diagnosis_dummy + EXCEPTION * diagnosis_dummy + (1 | LISTING_CTR_CODE), data = cand_hx_list_episodes_grouping)


summary(fourth_model_death)
exp(confint(fourth_model_death))

# third_plot_death = plot_model(
#   third_model_death,
#   show.values = TRUE,
#   value.offset = .3,
#   value.size = 6,
#   # axis.labels = c(
#   #   "Status (Ref 2): 1A",
#   #   "Status (Ref 2): 1B",
#   #   "Exception"),
#   title = "",
#   axis.title = "Hazard Ratio of Pre-Transplant Mortality",
#   grid.breaks = c(0.1, 1, 10, 100)) +
#   theme_classic() +
#   theme(text = element_text(size = 20),
#         axis.text.x = element_text(size = 18),
#         axis.title.x = element_text(size = 20),
#         axis.text.y = element_text(size = 18),
#         axis.title.y = element_text(size = 20),
#         legend.text = element_text(size = 20),
#         legend.title = element_text(size = 20)) +
#   geom_hline(yintercept = 1, linetype = "dotted", linewidth = 1, color = "black")



  
  # ============================================================================
# ANALYSIS: Exception Effect by Diagnosis Using emmeans
# ============================================================================

library(coxme)
library(emmeans)
library(ggplot2)
library(dplyr)
library(tibble)

# Your interaction model (already fitted)
# fourth_model_death <- coxme(Surv(start, end, death) ~ STATUS + EXCEPTION + 
#                              diagnosis_dummy + EXCEPTION * diagnosis_dummy + 
#                              (1 | LISTING_CTR_CODE), 
#                              data = cand_hx_list_episodes_grouping)

# ----------------------------------------------------------------------------
# Approach 1: Using emmeans (if it works with coxme)
# ----------------------------------------------------------------------------

# Try emmeans - may need to use mode = "linear.predictor"
emm_results <- emmeans(fourth_model_death, 
                       specs = ~ EXCEPTION | diagnosis_dummy,
                       mode = "linear.predictor",
                       type = "response")

# Get contrasts (exception vs no exception within each diagnosis)
exception_contrasts <- contrast(emm_results, 
                                method = "pairwise",
                                type = "response")

# View results
summary(exception_contrasts)

# ----------------------------------------------------------------------------
# Approach 2: Manual Calculation (More reliable for coxme)
# ----------------------------------------------------------------------------

# Extract coefficients and variance-covariance matrix
coefs <- fixef(fourth_model_death)
vcov_matrix <- vcov(fourth_model_death)

# Calculate exception effect for each diagnosis
# Reference (DCM): Just the main effect
# CHD: main effect + interaction
# Re-Tx: main effect + interaction  
# Other: main effect + interaction

# Create contrast matrix
# Rows: DCM, CHD, Re-Tx, Other
# Columns: coefficients in order from model

# Get coefficient names
names(coefs)

# Manual calculation for each diagnosis
calc_exception_hr <- function(main_effect, interaction_effect = 0, 
                              vcov_matrix, main_idx, int_idx = NULL) {
  
  if(is.null(int_idx)) {
    # Reference group (DCM)
    log_hr <- main_effect
    se <- sqrt(vcov_matrix[main_idx, main_idx])
  } else {
    # Other groups with interaction
    log_hr <- main_effect + interaction_effect
    # Variance: Var(A+B) = Var(A) + Var(B) + 2*Cov(A,B)
    var <- vcov_matrix[main_idx, main_idx] + 
           vcov_matrix[int_idx, int_idx] + 
           2 * vcov_matrix[main_idx, int_idx]
    se <- sqrt(var)
  }
  
  hr <- exp(log_hr)
  ci_lower <- exp(log_hr - 1.96 * se)
  ci_upper <- exp(log_hr + 1.96 * se)
  z <- log_hr / se
  p_value <- 2 * pnorm(-abs(z))
  
  return(data.frame(
    log_hr = log_hr,
    hr = hr,
    se = se,
    ci_lower = ci_lower,
    ci_upper = ci_upper,
    z = z,
    p_value = p_value
  ))
}

# Get coefficient indices
exception_idx <- which(names(coefs) == "EXCEPTION")
chd_int_idx <- which(names(coefs) == "EXCEPTION:diagnosis_dummyCongenital Heart Disease")
retx_int_idx <- which(names(coefs) == "EXCEPTION:diagnosis_dummyRe-Heart Transplant")
other_int_idx <- which(names(coefs) == "EXCEPTION:diagnosis_dummyOther")

# Calculate for each diagnosis
dcm_result <- calc_exception_hr(
  main_effect = coefs[exception_idx],
  vcov_matrix = vcov_matrix,
  main_idx = exception_idx
)

chd_result <- calc_exception_hr(
  main_effect = coefs[exception_idx],
  interaction_effect = coefs[chd_int_idx],
  vcov_matrix = vcov_matrix,
  main_idx = exception_idx,
  int_idx = chd_int_idx
)

retx_result <- calc_exception_hr(
  main_effect = coefs[exception_idx],
  interaction_effect = coefs[retx_int_idx],
  vcov_matrix = vcov_matrix,
  main_idx = exception_idx,
  int_idx = retx_int_idx
)

other_result <- calc_exception_hr(
  main_effect = coefs[exception_idx],
  interaction_effect = coefs[other_int_idx],
  vcov_matrix = vcov_matrix,
  main_idx = exception_idx,
  int_idx = other_int_idx
)

# Combine results
diagnosis_results <- bind_rows(
  dcm_result %>% mutate(diagnosis = "Dilated Cardiomyopathy"),
  chd_result %>% mutate(diagnosis = "Congenital Heart Disease"),
  retx_result %>% mutate(diagnosis = "Re-Heart Transplant"),
  other_result %>% mutate(diagnosis = "Other")
)

# Add sample sizes (you'll need to calculate these from your data)
# Get counts from your dataset
diagnosis_counts <- cand_hx_list_episodes_grouping %>%
  group_by(diagnosis_dummy) %>%
  summarise(
    n_patients = n_distinct(PX_ID),
    n_deaths = sum(death, na.rm = TRUE)
  )

# Print results
print(diagnosis_results)

# ----------------------------------------------------------------------------
# Likelihood Ratio Test for Interaction
# ----------------------------------------------------------------------------

# Fit model without interaction
model_no_interaction <- coxme(Surv(start, end, death) ~ STATUS + EXCEPTION + 
                               diagnosis_dummy + (1 | LISTING_CTR_CODE), 
                               data = cand_hx_list_episodes_grouping)

# Compare models
lr_test <- anova(model_no_interaction, fourth_model_death)
print(lr_test)

# Extract p-value for interaction
interaction_p <- lr_test[2, "P(>|Chi|)"]
cat("\nInteraction p-value:", interaction_p, "\n")

# ============================================================================
# FIGURE: Forest Plot of Exception Effects by Diagnosis
# ============================================================================

# Prepare data for plotting
plot_data <- diagnosis_results %>%
  mutate(
    diagnosis = factor(diagnosis, 
                      levels = c("Other", "Re-Heart Transplant", 
                                "Congenital Heart Disease", 
                                "Dilated Cardiomyopathy")),
    # Create label with HR and CI
    label = sprintf("%.2f (%.2f-%.2f)", hr, ci_lower, ci_upper),
    # Create p-value label
    p_label = case_when(
      p_value < 0.001 ~ "***",
      p_value < 0.01 ~ "**",
      p_value < 0.05 ~ "*",
      TRUE ~ ""
    )
  )

# Add overall result from Primary Model 1
overall_result <- data.frame(
  diagnosis = factor("Overall (Primary Model 1)", 
                    levels = c("Overall (Primary Model 1)", "Other", 
                              "Re-Heart Transplant", "Congenital Heart Disease",
                              "Dilated Cardiomyopathy")),
  hr = 0.41,  # From your Primary Model 1
  ci_lower = 0.31,
  ci_upper = 0.55,
  p_value = 0.001,
  label = "0.41 (0.31-0.55)",
  p_label = "***"
)

# Combine with diagnosis-specific results
plot_data_full <- bind_rows(overall_result, plot_data) %>%
  mutate(
    diagnosis = factor(diagnosis, 
                      levels = c("Overall (Primary Model 1)", "Other",
                                "Re-Heart Transplant", "Congenital Heart Disease",
                                "Dilated Cardiomyopathy"))
  )

# Create forest plot
forest_plot <- ggplot(plot_data_full, aes(x = hr, y = diagnosis)) +
  # Add vertical line at HR = 1
  geom_vline(xintercept = 1, linetype = "dashed", color = "gray50", linewidth = 0.5) +
  
  # Add confidence intervals
  geom_errorbarh(aes(xmin = ci_lower, xmax = ci_upper), 
                 height = 0.2, linewidth = 0.8, color = "black") +
  
  # Add point estimates
  geom_point(aes(shape = diagnosis, fill = diagnosis), 
             size = 4, color = "black") +
  
  # Styling for overall vs. subgroup
  scale_shape_manual(values = c(23, 21, 21, 21, 21)) +  # Diamond for overall, circles for subgroups
  scale_fill_manual(values = c("black", "#E69F00", "#56B4E9", "#009E73", "#CC79A7")) +
  
  # Add HR labels
  geom_text(aes(label = label), 
            hjust = 0, nudge_y = 0.25, size = 3.5, fontface = "bold") +
  
  # Add p-value stars
  geom_text(aes(label = p_label, x = ci_upper), 
            hjust = -1.5, size = 4) +
  
  # Scale and labels
  scale_x_continuous(
    trans = "log",
    breaks = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.75, 1.0, 1.5),
    labels = c("0.1", "0.2", "0.3", "0.4", "0.5", "0.75", "1.0", "1.5"),
    limits = c(0.1, 1.8)
  ) +
  
  labs(
    x = "Hazard Ratio for Exceptions",
    y = NULL,
    #title = "Association Between Status Exceptions and Waitlist Mortality",
    #subtitle = sprintf("Stratified by Primary Diagnosis (Interaction p = %.3f)", interaction_p),
    caption = "* p < 0.05, ** p < 0.01, *** p < 0.001"
  ) +
  
  theme_classic(base_size = 12) +
  theme(
    legend.position = "none",
    axis.text.y = element_text(size = 11, face = "bold"),
    axis.text.x = element_text(size = 10),
    axis.title.x = element_text(size = 11, face = "bold", margin = margin(t = 10)),
    plot.title = element_text(size = 13, face = "bold", hjust = 0),
    plot.subtitle = element_text(size = 11, hjust = 0, margin = margin(b = 10)),
    plot.caption = element_text(size = 9, hjust = 0, margin = margin(t = 10)),
    panel.grid.major.x = element_line(color = "gray90", linewidth = 0.3),
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank()
  )

print(forest_plot)

interaction_p

```






``` {r third cox model assumptions}

library(survival)
library(coxme)
library(car)
library(dplyr)

# ===== 1. CHECK PROPORTIONAL HAZARDS =====
# Fit Cox without random effects
cox_no_re <- coxph(Surv(start, end, death) ~ STATUS_JUST, 
                   data = cand_hx_list_episodes_grouping)

ph_test <- cox.zph(cox_no_re)
print(ph_test)  # p > 0.05 = assumption met
plot(ph_test)   # Flat lines = good

# ===== 2. CHECK NORMALITY OF RANDOM EFFECTS =====
frailty_values <- ranef(third_model_death)$LISTING_CTR_CODE

# QQ plot
qqnorm(frailty_values, main = "Q-Q Plot of Center Random Effects")
qqline(frailty_values, col = "red")

# Shapiro-Wilk test
shapiro_result <- shapiro.test(frailty_values)
print(paste0("Shapiro-Wilk test p-value: ", round(shapiro_result$p.value, 3)))

# Histogram
hist(frailty_values, breaks = 20,
     main = "Distribution of Center Random Effects",
     xlab = "Random Effect (Frailty)")


# ===== 4. CHECK CLUSTER SIZE ADEQUACY =====
cluster_summary <- cand_hx_list_episodes_grouping %>%
  group_by(LISTING_CTR_CODE) %>%
  summarise(
    n_episodes = n(),
    n_deaths = sum(death),
    death_rate = mean(death)
  ) %>%
  arrange(n_episodes)

print(summary(cluster_summary))

# Count small clusters
small_clusters <- cluster_summary %>%
  filter(n_episodes < 10 | n_deaths < 5)
print(paste0("Small clusters: ", nrow(small_clusters), " out of ", nrow(cluster_summary)))

# ===== 5. SENSITIVITY ANALYSIS - EXCLUDE SMALL CENTERS =====
adequate_centers <- cluster_summary %>%
  filter(n_episodes >= 10, n_deaths >= 5) %>%
  pull(LISTING_CTR_CODE)

print(paste0("Adequate centers: ", length(adequate_centers), " out of 84"))

# Filter to adequate centers
cand_adequate <- cand_hx_list_episodes_grouping %>%
  filter(LISTING_CTR_CODE %in% adequate_centers)

# Refit model
model_sensitivity <- coxme(Surv(start, end, death) ~ STATUS_JUST + 
                            (1 | LISTING_CTR_CODE), 
                           data = cand_adequate)

# Compare fixed effects
comparison <- data.frame(
  Variable = names(fixef(third_model_death)),
  All_Centers_HR = exp(fixef(third_model_death)),
  Adequate_Centers_HR = exp(fixef(model_sensitivity)),
  Percent_Change = (exp(fixef(model_sensitivity)) - exp(fixef(third_model_death))) / 
                   exp(fixef(third_model_death)) * 100
)

print("Fixed effects comparison:")
print(comparison)



```



``` {r cif}

#this code creates Figure 2

admin_censor_date = as.Date("2025-06-30")

init_status_1a = fortable1 %>% 
  filter(initial_status == "1A") %>%
  mutate(
    competing_outcome = case_when(
      REM_CD %in% c(8, 13) ~ 1,
      !is.na(TX_DATE) & REM_CD == 4 ~ 2,
      REM_CD == 12 ~ 3,
      TRUE ~ 0),
    competing_outcome_date = case_when(
      competing_outcome != 0 ~ END_DATE,
      competing_outcome == 0 & !is.na(REM_CD) ~ END_DATE,
      TRUE ~ admin_censor_date),
    competing_outcome = as.factor(competing_outcome),
    competing_time = as.numeric(competing_outcome_date - INIT_DATE)) %>%
  mutate(
    death = ifelse(REM_CD %in% c(8, 13), 1, 0),
    end_date = case_when(
      death == 1 ~ END_DATE,
      death == 0 & !is.na(REM_CD) ~ END_DATE,
      TRUE ~ admin_censor_date),
    time = as.numeric(end_date - INIT_DATE),
    status_1a_just_labels = case_when(
      STATUS_JUST == "Status 1A: Exception" ~ "Exception",
      STATUS_JUST == "Status 1A: Congenital Heart Disease" ~ "Congenital Heart Disease with Inotropes",
      STATUS_JUST == "Status 1A: Ductal-Dependent Circulation" ~ "Ductal-Dependent Circulation",
      STATUS_JUST == "Status 1A: MCS/IABP" ~ "MCS/IABP",
      STATUS_JUST == "Status 1A: Mechanical Ventilation" ~ "Mechanical Ventilation"),
    status_1a_just_labels = factor(status_1a_just_labels, c("Exception", "Congenital Heart Disease with Inotropes", "Ductal-Dependent Circulation", "MCS/IABP", "Mechanical Ventilation")))



init_status_1b = fortable1 %>% 
  filter(initial_status == "1B") %>%
  mutate(
    competing_outcome = case_when(
      REM_CD %in% c(8, 13) ~ 1,
      !is.na(TX_DATE) & REM_CD == 4 ~ 2,
      REM_CD == 12 ~ 3,
      TRUE ~ 0),
    competing_outcome_date = case_when(
      competing_outcome != 0 ~ END_DATE,
      competing_outcome == 0 & !is.na(REM_CD) ~ END_DATE,
      TRUE ~ admin_censor_date),
    competing_outcome = as.factor(competing_outcome),
    competing_time = as.numeric(competing_outcome_date - INIT_DATE)) %>%
  mutate(
    death = ifelse(REM_CD %in% c(8, 13), 1, 0),
    end_date = case_when(
      death == 1 ~ END_DATE,
      death == 0 & !is.na(REM_CD) ~ END_DATE,
      TRUE ~ admin_censor_date),
    time = as.numeric(end_date - INIT_DATE),
    status_1b_just_labels = case_when(
      STATUS_JUST == "Status 1B: Exception" ~ "Exception",
      STATUS_JUST == "Status 1B: Standard 1B Listing" ~ "Standard Listing"),
    status_1b_just_labels = factor(status_1b_just_labels, c("Exception", "Standard Listing")))


library(tidyverse)
library(survival)
library(cmprsk)
library(tidycmprsk)
library(ggsurvfit)
library(ggsci)
library(scales)
# Your dataset is ready - init_status_1a

# Verify the competing outcome coding
table(init_status_1a$competing_outcome, useNA = "always")
# 0 = censored, 1 = death/deterioration, 2 = transplant, 3 = recovery

# Verify STATUS_JUST labels
table(init_status_1a$status_1a_just_labels, useNA = "always")

# Remove any missing STATUS_JUST
init_status_1a_clean <- init_status_1a %>%
  filter(!is.na(status_1a_just_labels))

# ============================================================================
# METHOD 1: Using tidycmprsk (Recommended - easier and cleaner)
# ============================================================================

# Create cumulative incidence object
cuminc_obj <- cuminc(
  Surv(competing_time, competing_outcome) ~ status_1a_just_labels,
  data = init_status_1a_clean
)

# Test for differences between groups
# This tests if cumulative incidence curves differ by STATUS_JUST
# for outcome = 1 (death/deterioration)
print(cuminc_obj)

# Extract p-value for death/deterioration outcome
cif_direct <- cmprsk::cuminc(
  ftime = init_status_1a_clean$competing_time,
  fstatus = init_status_1a_clean$competing_outcome,
  group = init_status_1a_clean$status_1a_just_labels,
  cencode = 0
)

# Print test results
print("\n=== Gray's Test Results ===")
print(cif_direct$Tests)

# Extract p-value for outcome 1 (death/deterioration)
# Row 1 = outcome 1, Column 2 = p-value
pval_death <- cif_direct$Tests[1, 2]
cat("\nP-value for death/deterioration:", pval_death, "\n")

# Format p-value for plot
pval_text <- if_else(pval_death < 0.001, 
                     "Gray's test p < 0.001",
                     sprintf("Gray's test p = %.3f", pval_death))

# ============================================================================
# Cumulative Incidence Analysis for Status 1A by Indication
# ============================================================================

library(tidyverse)
library(survival)
library(cmprsk)
library(tidycmprsk)
library(ggsurvfit)

# ============================================================================
# Get p-value using cmprsk directly
# ============================================================================

cif_direct <- cmprsk::cuminc(
  ftime = init_status_1a_clean$competing_time,
  fstatus = init_status_1a_clean$competing_outcome,
  group = init_status_1a_clean$status_1a_just_labels,
  cencode = 0
)

# Extract p-value for outcome 1 (death/deterioration)
pval_death <- cif_direct$Tests[1, 2]
cat("P-value for death/deterioration:", pval_death, "\n")

# Format p-value for plot
pval_text <- if_else(pval_death < 0.001, 
                     "Gray's test p < 0.001",
                     sprintf("Gray's test p = %.3f", pval_death))

# ============================================================================
# Create tidycmprsk object for plotting
# ============================================================================

cuminc_obj <- cuminc(
  Surv(competing_time, competing_outcome) ~ status_1a_just_labels,
  data = init_status_1a_clean
)

fig <- cuminc_obj %>%
  ggcuminc(outcome = "1", linewidth = 1.2) +
  add_confidence_interval() +
  
  scale_color_manual(
    values = c(
      "Exception" = "#374e55",
      "Congenital Heart Disease with Inotropes" = "#79af97",
      "Ductal-Dependent Circulation" = "#b24745",
      "MCS/IABP" = "#00a1d5",
      "Mechanical Ventilation" = "#df8f44"
    ),
    name = NULL  # Remove legend title
  ) +
  
  scale_fill_manual(
    values = c(
      "Exception" = "#374e55",
      "Congenital Heart Disease with Inotropes" = "#79af97",
      "Ductal-Dependent Circulation" = "#b24745",
      "MCS/IABP" = "#00a1d5",
      "Mechanical Ventilation" = "#df8f44"
    ),
    name = NULL  # Remove legend title
  ) +
  
  scale_y_continuous(
    limits = c(0, 0.4),
    labels = scales::percent, 
    expand = c(0.01, 0)
  ) +
  
  scale_x_continuous(
    limits = c(0, 365),
    breaks = seq(0, 365, 60),
    expand = expansion(mult = c(0.05, 0.05))
  ) +
  
  labs(
    x = "Days after Initial Listing",
    y = "Cumulative Incidence of Death\nor Clinical Deterioration",
    title = ""
  ) +
  
  guides(
    color = guide_legend(nrow = 2, byrow = TRUE),
    fill = guide_legend(nrow = 2, byrow = TRUE),
    linetype = guide_legend(nrow = 2, byrow = TRUE, override.aes = list(fill = NA))
  ) +
  
  annotate(
    "text",
    x = 90, y = 0.35,
    label = pval_text,
    size = 4,
    hjust = 1
  ) +
  
  theme_classic(base_size = 14) +
  theme(
    legend.title = element_blank(),  # Use element_blank() not element_text("")
    legend.text = element_text(size = 14),
    legend.position = "bottom",
    legend.box = "horizontal",
    axis.title = element_text(face = "bold", size = 14),
    plot.title = element_text(face = "bold", size = 14, hjust = 0),
    panel.grid.major.y = element_line(color = "gray90", linewidth = 0.3)
  ) +
  
  add_risktable(
    times = seq(0, 360, 60),
    size = 5,
    theme = theme_risktable_default(
      axis.text.y.size = 14,
      plot.title.size = 14
    )
  )

print(fig)


# Create cuminc object (if not already created)
cuminc_obj <- cuminc(
  Surv(competing_time, competing_outcome) ~ status_1a_just_labels,
  data = init_status_1a_clean
)


ci_all_outcomes <- cuminc_obj %>%
  tidy() %>%
  filter(time <= 365) %>%
  group_by(strata, outcome) %>%
  slice_max(time, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  mutate(
    outcome_label = case_when(
      outcome == "1" ~ "Death/Deterioration",
      outcome == "2" ~ "Transplant",
      outcome == "3" ~ "Recovery",
      TRUE ~ "Other"
    ),
    ci_percent = estimate * 100,
    ci_formatted = sprintf("%.1f%% (%.1f%%, %.1f%%)", 
                           estimate * 100, 
                           conf.low * 100, 
                           conf.high * 100)
  ) %>%
  dplyr::select(strata, outcome, outcome_label, time, 
         ci_percent, estimate, conf.low, conf.high, ci_formatted)

print("\n=== Cumulative Incidence at 365 Days - All Outcomes ===")
print(ci_all_outcomes)

```


``` {r central illustration}


# ============================================================================
# Forest Plot for Primary Model 2 (Status 2 Reference)
# ============================================================================

library(tidyverse)

# ============================================================================
# Extract Model Results and Add Reference Category
# ============================================================================

results <- data.frame(
  category = c(
    "Status 2",  # Reference category
    "Status 1B: Exception",
    "Status 1B: Standard Listing",
    "Status 1A: Exception",
    "Status 1A: Congenital Heart Disease",
    "Status 1A: Ductal-Dependent Circulation",
    "Status 1A: MCS/IABP",
    "Status 1A: Mechanical Ventilation"
  ),
  hr = c(
    1.00,  # Reference
    1.5274,
    2.0300,
    4.0820,
    10.8083,
    15.1575,
    11.1448,
    50.7471
  ),
  log_hr = c(
    0,  # Reference
    0.4236,
    0.7080,
    1.4066,
    2.3803,
    2.7185,
    2.4110,
    3.9269
  ),
  se = c(
    0,  # Reference
    0.2636,
    0.2642,
    0.2680,
    0.1914,
    0.2154,
    0.1872,
    0.1926
  ),
  p_value = c(
    NA,  # Reference
    0.10808,
    0.00736,
    1.53e-07,
    2e-16,
    2e-16,
    2e-16,
    2e-16
  )
) %>%
  mutate(
    # Calculate confidence intervals
    ci_lower = exp(log_hr - 1.96 * se),
    ci_upper = exp(log_hr + 1.96 * se),
    # Format for display
    hr_ci = ifelse(category == "Status 2",
                   "1.00 (Reference)",
                   sprintf("%.2f (%.2f, %.2f)", hr, ci_lower, ci_upper)),
    # P-value formatting
    p_formatted = case_when(
      is.na(p_value) ~ "—",
      p_value < 0.001 ~ "<0.001",
      TRUE ~ sprintf("%.3f", p_value)
    ),
    # Clean category names
    category_clean = str_replace(category, "Status 1A: ", "1A: "),
    category_clean = str_replace(category_clean, "Status 1B: ", "1B: "),
    # Add grouping
    group = case_when(
      str_detect(category, "Status 1A") ~ "Status 1A",
      str_detect(category, "Status 1B") ~ "Status 1B",
      str_detect(category, "Status 2") ~ "Status 2"
    ),
    # Order categories
    order = c(1, 2, 3, 4, 5, 6, 7, 8)
  ) %>%
  arrange(order)

# ============================================================================
# Create Forest Plot Using ggplot2
# ============================================================================

forest_plot <- ggplot(results, aes(y = reorder(category_clean, -order))) +
  
  # Add reference line at HR = 1
  geom_vline(xintercept = 1, linetype = "dashed", color = "gray50", linewidth = 0.5) +
  
  # Add confidence intervals
  geom_errorbarh(
    aes(xmin = ci_lower, xmax = ci_upper),
    height = 0.2,
    linewidth = 0.8,
    color = "black"
  ) +
  
  # Add point estimates
  geom_point(
    aes(x = hr, shape = group, fill = group),
    size = 4,
    color = "black"
  ) +
  
  # Shapes and colors by status group
  scale_shape_manual(
    values = c("Status 1A" = 21, "Status 1B" = 22, "Status 2" = 24),
    guide = "none"
  ) +
  
  scale_fill_manual(
    values = c("Status 1A" = "#d55e00", "Status 1B" = "#0072b2", "Status 2" = "#009e73"),
    guide = "none"
  ) +
  
  # Log scale for x-axis
  scale_x_continuous(
    trans = "log",
    breaks = c(1, 2, 5, 10, 20, 50, 100),
    labels = c("1", "2", "5", "10", "20", "50", "100"),
    limits = c(0.5, 100)
  ) +
  
  # Labels
  labs(
    x = "Hazard Ratio for Waitlist Mortality",
    y = NULL,
    title = "Association Between Listing Status/Indication and Waitlist Mortality",
    subtitle = "Reference: Status 2"
  ) +
  
  # Theme
  theme_classic(base_size = 12) +
  theme(
    axis.text.y = element_text(size = 11, face = "bold"),
    axis.text.x = element_text(size = 10),
    axis.title.x = element_text(size = 11, face = "bold", margin = margin(t = 10)),
    plot.title = element_text(size = 13, face = "bold", hjust = 0),
    plot.subtitle = element_text(size = 11, hjust = 0, margin = margin(b = 10)),
    panel.grid.major.x = element_line(color = "gray90", linewidth = 0.3),
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank()
  )

print(forest_plot)

# ============================================================================
# Add Text Annotations with HR and P-values
# ============================================================================

forest_plot_annotated <- forest_plot +
  
  # Add HR (95% CI) text to the right
  geom_text(
    aes(x = 90, label = hr_ci),
    hjust = 0,
    size = 3.5,
    fontface = "bold"
  ) +
  
  # Add p-values further right
  geom_text(
    aes(x = 120, label = p_formatted),
    hjust = 0.5,
    size = 3.5
  ) +
  
  # Expand limits to accommodate text
  coord_cartesian(xlim = c(0.5, 140), clip = "off") +
  
  # Add column headers
  annotate("text", x = 90, y = 8.5, label = "HR (95% CI)", 
           hjust = 0, fontface = "bold", size = 3.5) +
  annotate("text", x = 120, y = 8.5, label = "P-value", 
           hjust = 0.5, fontface = "bold", size = 3.5) +
  
  # Adjust plot margins to accommodate text
  theme(plot.margin = margin(10, 100, 10, 10))

print(forest_plot_annotated)


``` 


``` {r cif for 1b}




# Verify the competing outcome coding
table(init_status_1b$competing_outcome, useNA = "always")
# 0 = censored, 1 = death/deterioration, 2 = transplant, 3 = recovery

# Verify STATUS_JUST labels
table(init_status_1b$status_1b_just_labels, useNA = "always")

# Remove any missing STATUS_JUST
init_status_1b_clean <- init_status_1b %>%
  filter(!is.na(status_1b_just_labels))

# ============================================================================
# METHOD 1: Using tidycmprsk (Recommended - easier and cleaner)
# ============================================================================

# Create cumulative incidence object
cuminc_obj1b <- cuminc(
  Surv(competing_time, competing_outcome) ~ status_1b_just_labels,
  data = init_status_1b_clean
)

# Test for differences between groups
# This tests if cumulative incidence curves differ by STATUS_JUST
# for outcome = 1 (death/deterioration)
print(cuminc_obj1b)

# Extract p-value for death/deterioration outcome
cif_direct1b <- cmprsk::cuminc(
  ftime = init_status_1b_clean$competing_time,
  fstatus = init_status_1b_clean$competing_outcome,
  group = init_status_1b_clean$status_1b_just_labels,
  cencode = 0
)

# Print test results
print("\n=== Gray's Test Results ===")
print(cif_direct1b$Tests)

# Extract p-value for outcome 1 (death/deterioration)
# Row 1 = outcome 1, Column 2 = p-value
pval_death <- cif_direct1b$Tests[1, 2]
cat("\nP-value for death/deterioration:", pval_death, "\n")

# Format p-value for plot
pval_text <- if_else(pval_death < 0.001, 
                     "Gray's test p < 0.001",
                     sprintf("Gray's test p = %.3f", pval_death))

# ============================================================================
# Cumulative Incidence Analysis for Status 1B by Indication
# ============================================================================

library(tidyverse)
library(survival)
library(cmprsk)
library(tidycmprsk)
library(ggsurvfit)

# ============================================================================
# Get p-value using cmprsk directly
# ============================================================================


fig1 <- cuminc_obj1b %>%
  ggcuminc(outcome = "1", linewidth = 1.2) +
  add_confidence_interval() +
  
  scale_color_manual(
    values = c(
      "Exception" = "#374e55",
      "Standard Listing" = "#b24745"
    ),
    name = NULL
  ) +
  
  scale_fill_manual(
    values = c(
      "Exception" = "#374e55",
      "Standard Listing" = "#b24745"
    ),
    name = NULL
  ) +
  
  scale_y_continuous(
    limits = c(0, 0.2),
    labels = scales::percent, 
    expand = c(0.01, 0)
  ) +
  
  scale_x_continuous(
    limits = c(0, 365),
    breaks = seq(0, 365, 60),
    expand = expansion(mult = c(0.05, 0.05))
  ) +
  
  labs(
    x = "Days after Initial Listing",
    y = "Cumulative Incidence",
    #title = "Cumulative Incidence by Status 1A Indication"
  ) +
  
  guides(
    color = guide_legend(nrow = 1, byrow = TRUE),
    fill = guide_legend(nrow = 1, byrow = TRUE),
    linetype = guide_legend(nrow = 1, byrow = TRUE, override.aes = list(fill = NA))
  ) +
  
  annotate(
    "text",
    x = 300, y = 0.15,
    label = pval_text,
    size = 5,
    hjust = 1
  ) +
  
  theme_classic(base_size = 14) +
  theme(
    legend.title = element_blank(),
    legend.text = element_text(size = 14),
    legend.position = "bottom",
    legend.box = "horizontal",
    axis.title = element_text(face = "bold", size = 14),
    plot.title = element_text(face = "bold", size = 14, hjust = 0),
    panel.grid.major.y = element_line(color = "gray90", linewidth = 0.3)
  ) +
  
  add_risktable(
    times = seq(0, 360, 60),
    size = 5,
    theme = theme_risktable_default(
      axis.text.y.size = 14,
      plot.title.size = 14
    )
  )

print(fig1)



# ============================================================================
# Get Cumulative Incidence at 1 Year
# ============================================================================

ci_at_1year_1b <- cuminc_obj1b %>%
  tidy() %>%
  filter(outcome == "1", time <= 365) %>%
  group_by(strata) %>%
  slice_max(time, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  mutate(
    ci_formatted = sprintf("%.1f%% (%.1f%%, %.1f%%)", 
                          estimate * 100, conf.low * 100, conf.high * 100)
  ) %>%
  dplyr::select(strata, time, estimate, conf.low, conf.high, ci_formatted)

print("\n=== Cumulative Incidence at 1 Year ===")
print(ci_at_1year_1b)

```


``` {r figure 1}

fortable1 = fortable1 %>%
  mutate(
    competing_outcome = case_when(
      REM_CD %in% c(8, 13) ~ 1,
      !is.na(TX_DATE) & REM_CD == 4 ~ 2,
      REM_CD == 12 ~ 3,
      TRUE ~ 0),
    competing_outcome_date = case_when(
      competing_outcome != 0 ~ END_DATE,
      competing_outcome == 0 & !is.na(REM_CD) ~ END_DATE,
      TRUE ~ admin_censor_date),
    competing_time = as.numeric(competing_outcome_date - INIT_DATE))

justtransplants = fortable1 %>% filter(competing_outcome == 2) 
median(justtransplants$competing_time)

just1a = fortable1 %>% filter(initial_status == "1A")
summary(just1a$competing_time)

just1b = fortable1 %>% filter(initial_status == "1B")
summary(just1b$competing_time)

just2 = fortable1 %>% filter(initial_status == "2")
summary(just2$competing_time)

options("ggsurvfit.switch-color-linetype" = TRUE)

cif_fit = cuminc(Surv(competing_time, as.factor(competing_outcome)) ~ 1, data = fortable1)

cif_fit = cif_fit %>%
  ggcuminc(outcome = c("1", "2", "3")) +
  add_confidence_interval() +
  coord_cartesian(xlim = c(0, 360)) +
  scale_x_continuous(breaks = c(0, 60, 120, 180, 240, 300, 360)) +
  scale_y_continuous(
    limits = c(0, 1),
    labels = scales::percent, 
    expand = c(0.01, 0)
  ) +
  add_risktable(times = seq(0, 360, 60), size = 6,
                theme = theme_risktable_default(axis.text.y.size = 18)) +
  scale_x_continuous(limits = c(0, 360), breaks = seq(0, 360, 60)) +
  scale_color_manual(name = "Outcome",
                     values = c("1" = "#374e55", "2" = "#df8f44", "3" = "#00a1d5"),
                     labels = c("Death/Clinical Deterioration", "Transplant", "Removal for Clinical Recovery")) +
  scale_fill_manual(name = "Outcome",
                    values = c("1" = "#374e55", "2" = "#df8f44", "3" = "#00a1d5"),
                    labels = c("Death/Clinical Deterioration", "Transplant", "Removal for Clinical Recovery")) +
  labs(x = "Days after Initial Listing", y = "Cumulative Incidence") +
  theme_classic() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(size = 18),
        axis.title.x = element_text(size = 20),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20),
        strip.text.y = element_text(size = 18))

# Fit the cumulative incidence model
cif_model <- cuminc(Surv(competing_time, as.factor(competing_outcome)) ~ 1, 
                    data = fortable1)

# Extract cumulative incidence at 365 days (or closest timepoint)
cif_365 <- cif_model %>%
  tidy() %>%
  filter(time <= 365) %>%
  group_by(outcome) %>%
  slice_max(time, n = 1) %>%
  ungroup() %>%
  select(outcome, time, estimate, conf.low, conf.high)

print(cif_365)

# Format as table
cif_365 %>%
  mutate(
    outcome_label = case_when(
      outcome == "1" ~ "Death/Clinical Deterioration",
      outcome == "2" ~ "Transplant",
      outcome == "3" ~ "Removal for Clinical Recovery"
    ),
    `Cumulative Incidence (95% CI)` = sprintf("%.1f%% (%.1f%% - %.1f%%)", 
                                               estimate*100, conf.low*100, conf.high*100)
  ) %>%
  select(Outcome = outcome_label, `Days` = time, `Cumulative Incidence (95% CI)`)


just1a1b = fortable1 %>% filter(initial_status != "2")

cif_fit1 = cuminc(Surv(competing_time, as.factor(competing_outcome)) ~ initial_status, data = fortable1)


cif_fit1 = cif_fit1 %>%
  ggcuminc(outcome = c("1", "2", "3")) +
  add_confidence_interval() +
  coord_cartesian(xlim = c(0, 360)) +
  scale_x_continuous(breaks = c(0, 60, 120, 180, 240, 300, 360)) +
  scale_y_continuous(
    limits = c(0, 1),
    labels = scales::percent, 
    expand = c(0.01, 0)
  ) +
  add_risktable(
    times = seq(0, 360, 60), 
    size = 6,
    risktable_height = 0.2,
    theme = list(
      theme_risktable_default(
        axis.text.y.size = 16,      # Controls "At Risk" and "Events" labels
        plot.title.size = 16         # Controls "1A" and "1B" strata labels
      ),
      theme(panel.spacing.y = unit(1, "pt"))
      #theme(plot.margin = margin(t = -5, r = 5, b = -5, l = 5, unit = "pt"))  # Reduce spacing between rows
    )
  ) +
  scale_x_continuous(limits = c(0, 360), breaks = seq(0, 360, 60)) +
  scale_color_manual(name = "Outcome",
                     values = c("1" = "#b24745", "2" = "#00a1d5", "3" = "#374e55"),
                     labels = c("Death/Clinical Deterioration", "Transplant", "Removal for Clinical Recovery")) +
  scale_fill_manual(name = "Outcome",
                    values = c("1" = "#b24745", "2" = "#00a1d5", "3" = "#374e55"),
                    labels = c("Death/Clinical Deterioration", "Transplant", "Removal for Clinical Recovery")) +
  scale_linetype_manual(name = "Status at Initial Listing",
                        values = c("1A" = "solid", "1B" = "dashed", "2" = "dotted"),
                        labels = c("1A", "1B", "2")) +
  guides(color = guide_legend(nrow = 3, byrow = TRUE),    # Force Outcome legend into 3 rows
         fill = guide_legend(nrow = 3, byrow = TRUE)) +
  guides(linetype = guide_legend(nrow = 3, byrow = TRUE,
                                 override.aes = list(fill = NA))) +
  labs(x = "Days after Initial Listing", y = "Cumulative Incidence") +
  theme_classic() +
  theme(text = element_text(size = 16),
        axis.text.x = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16),
        legend.position = "bottom",              # Move legends to bottom
        legend.box = "horizontal",  # Stack legends horizontally
        strip.text.y = element_text(size = 16))

# Fit the cumulative incidence model
cif_model1 <- cuminc(Surv(competing_time, as.factor(competing_outcome)) ~ initial_status, 
                     data = fortable1)

# Extract cumulative incidence at 365 days (or closest timepoint)
cif_365 <- cif_model1 %>%
  tidy() %>%
  filter(time <= 365) %>%
  group_by(outcome) %>%
  slice_max(time, n = 1) %>%
  ungroup() %>%
  select(outcome, time, estimate, conf.low, conf.high)

print(cif_365)

# Format as table
cif_365 %>%
  mutate(
    outcome_label = case_when(
      outcome == "1" ~ "Death/Clinical Deterioration",
      outcome == "2" ~ "Transplant",
      outcome == "3" ~ "Removal for Clinical Recovery"
    ),
    `Cumulative Incidence (95% CI)` = sprintf("%.1f%% (%.1f%% - %.1f%%)", 
                                               estimate*100, conf.low*100, conf.high*100)
  ) %>%
  select(Outcome = outcome_label, `Days` = time, `Cumulative Incidence (95% CI)`)


library(tidycmprsk)



deaths = cand_hx_list_episodes_grouping %>% filter(death == 1)
table(deaths$STATUS)





library(tidycmprsk)
library(gtsummary)

# Fine-Gray regression for each outcome
# Outcome 1: Death/Clinical Deterioration
crr_outcome1 <- crr(
  Surv(competing_time, as.factor(competing_outcome)) ~ initial_status, 
  data = fortable1,
  failcode = "1"  # The outcome of interest
)

# Outcome 2: Transplant
crr_outcome2 <- crr(
  Surv(competing_time, as.factor(competing_outcome)) ~ initial_status, 
  data = fortable1,
  failcode = "2"
)

# Outcome 3: Removal for Clinical Recovery
crr_outcome3 <- crr(
  Surv(competing_time, as.factor(competing_outcome)) ~ initial_status, 
  data = fortable1,
  failcode = "3"
)

# View results with tbl_regression
tbl_regression(crr_outcome1, exponentiate = TRUE)
tbl_regression(crr_outcome2, exponentiate = TRUE)
tbl_regression(crr_outcome3, exponentiate = TRUE)

# Or get summary statistics
summary(crr_outcome1)
summary(crr_outcome2)
summary(crr_outcome3)


p1 <- tidy(crr_outcome1)$p.value[1]
p2 <- tidy(crr_outcome2)$p.value[1]
p3 <- tidy(crr_outcome3)$p.value[1]

# Format p-values
p1_text <- ifelse(p1 < 0.001, "p < 0.001", sprintf("p = %.3f", p1))
p2_text <- ifelse(p2 < 0.001, "p < 0.001", sprintf("p = %.3f", p2))
p3_text <- ifelse(p3 < 0.001, "p < 0.001", sprintf("p = %.3f", p3))

# Add to plot
cif_fit1 +
  annotate("text", x = 100, y = 0.95, 
           label = paste0("Death/Deterioration: ", p1_text),
           size = 5, hjust = 1) +
  annotate("text", x = 100, y = 0.90, 
           label = paste0("Transplant: ", p2_text),
           size = 5, hjust = 1) +
  annotate("text", x = 100, y = 0.85, 
           label = paste0("Clinical Recovery: ", p3_text),
           size = 5, hjust = 1)




```



``` {r patient volumes by center}

library(dplyr)
library(ggplot2)

# Calculate patient volumes per center
center_volumes <- fortable1 %>%
  group_by(LISTING_CTR_CODE) %>%
  summarise(n_patients = n()) %>%
  arrange(desc(n_patients))

# Summary statistics
summary_stats <- center_volumes %>%
  summarise(
    n_centers = n(),
    mean = mean(n_patients),
    median = median(n_patients),
    Q1 = quantile(n_patients, 0.25),
    Q3 = quantile(n_patients, 0.75),
    IQR = IQR(n_patients),
    min = min(n_patients),
    max = max(n_patients)
  )

print(summary_stats)

# Calculate concentration metrics
concentration <- center_volumes %>%
  mutate(
    cumsum_patients = cumsum(n_patients),
    total_patients = sum(n_patients),
    cumulative_pct = cumsum_patients / total_patients * 100
  )

# Patients in top 25% of centers
top_25pct <- concentration %>%
  slice(1:ceiling(0.25 * nrow(.))) %>%
  summarise(pct_patients = last(cumulative_pct))

print(paste0("Top 25% of centers (n=", ceiling(0.25 * nrow(center_volumes)), 
             ") contain ", round(top_25pct$pct_patients, 1), "% of patients"))

# Histogram
ggplot(center_volumes, aes(x = n_patients)) +
  geom_histogram(bins = 20, fill = "steelblue", color = "black") +
  labs(x = "Number of Patients per Center",
       y = "Number of Centers",
       title = "Distribution of Patient Volumes Across Transplant Centers") +
  theme_classic()

# Create table for manuscript
volume_categories <- center_volumes %>%
  mutate(category = cut(n_patients, 
                        breaks = c(0, 25, 50, 100, 200, Inf),
                        labels = c("1-25", "26-50", "51-100", "101-200", ">200"),
                        right = TRUE)) %>%
  group_by(category) %>%
  summarise(
    n_centers = n(),
    pct_centers = n() / nrow(center_volumes) * 100,
    total_patients = sum(n_patients),
    pct_patients = total_patients / sum(center_volumes$n_patients) * 100
  )

print(volume_categories)


```



``` {r per status models}
#Status 1A ONLY

status1a <- cand_hx_list_episodes_grouping %>%
  filter(STATUS == "1A")

coxme_stat1a_death <- coxme(Surv(start, end, death) ~ EXCEPTION + (1 | LISTING_CTR_CODE), data = status1a)
# coxme_stat1a_transplant <- coxme(Surv(start, end, transplant) ~ EXCEPTION + (1 | LISTING_CTR_CODE), data = status1a)

summary(coxme_stat1a_death)
exp(confint(coxme_stat1a_death))
# 
# summary(coxme_stat1a_transplant)
# exp(confint(coxme_stat1a_transplant))

status1b <- cand_hx_list_episodes_grouping %>%
  filter(STATUS == "1B")

coxme_stat1b_death <- coxme(Surv(start, end, death) ~ EXCEPTION + (1 | LISTING_CTR_CODE), data = status1b)
# coxme_stat1b_transplant <- coxme(Surv(start, end, transplant) ~ EXCEPTION + (1 | LISTING_CTR_CODE), data = status1b)

summary(coxme_stat1b_death)
exp(confint(coxme_stat1b_death))
# 
# summary(coxme_stat1b_transplant)
# exp(confint(coxme_stat1b_transplant))

coxme_stats_ex <- plot_models(
  coxme_stat1a_death,
  coxme_stat1b_death,
  axis.labels = "Exception",
  m.labels = c("Status 1A", "Status 1B"),
  value.size = 6,
  # title = "Mixed Effects Model with Center Random Effects",
  legend.title = "",
  axis.title = "Hazard Ratio",
  spacing = 1,
  show.values = TRUE,
  show.p = TRUE,
  grid.breaks = c(0.1, 1, 10)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(size = 18),
        axis.title.x = element_text(size = 20),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)) +
  geom_hline(yintercept = 1, linetype = "dotted", linewidth = 1, color = "black")


```




``` {r nhrb and exception interaction}


cand_hx_list_episodes_pre_nhrb = cand_hx_list_episodes_grouping %>% filter(period == "pre-nhrb") %>%
  filter(CHG_DATE <= mdy("05-31-2021")) %>%
  mutate(
    death = case_when(
      death == 1 & CHG_END_DATE > mdy("05-31-2021") ~ 0,
      TRUE ~ death),
    transplant = case_when(
      transplant == 1 & CHG_END_DATE > mdy("05-31-2021") ~ 0,
      TRUE ~ transplant))


cand_hx_list_episodes_post_nhrb = cand_hx_list_episodes_grouping %>% filter(period == "post-nhrb") %>%
  filter(CHG_DATE <= mdy("05-31-2025")) %>%
  mutate(
    death = case_when(
      death == 1 & CHG_END_DATE > mdy("05-31-2025") ~ 0,
      TRUE ~ death),
    transplant = case_when(
      transplant == 1 & CHG_END_DATE > mdy("05-31-2025") ~ 0,
      TRUE ~ transplant))

nhrb_data = rbind(cand_hx_list_episodes_pre_nhrb, cand_hx_list_episodes_post_nhrb)


interaction_model <- coxme(Surv(start, end, death) ~ EXCEPTION * period + STATUS + EXCEPTION + period + (1 | LISTING_CTR_CODE), data = nhrb_data)

summary(interaction_model)
exp(confint(interaction_model))


interaction_model_plot = plot_model(
  interaction_model,
  show.values = TRUE,
  value.offset = .3,
  value.size = 6,
  axis.labels = c(
    "Exception & Cohort Interaction",
    "Status (Ref 2): 1A",
    "Status (Ref 2): 1B",
    "Policy Cohort: Pre NHRB",
    "Exception"),
  title = "",
  axis.title = "Hazard Ratio of Pre-Transplant Mortality",
  grid.breaks = c(0.1, 1, 10, 100)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(size = 18),
        axis.title.x = element_text(size = 20),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20)) +
  geom_hline(yintercept = 1, linetype = "dotted", linewidth = 1, color = "black")



library(emmeans)
library(ggplot2)

# Get estimated marginal means
emm <- emmeans(interaction_model, ~ EXCEPTION | period, type = "response")
emm_df <- as.data.frame(emm)

# Make sure EXCEPTION is a factor and relevel period
emm_df$EXCEPTION <- factor(emm_df$EXCEPTION, 
                           levels = c(0, 1),
                           labels = c("No Exception", "Exception"))
emm_df$period <- factor(emm_df$period, 
                        levels = c("pre-nhrb", "post-nhrb"),
                        labels = c("Pre-NHRB", "Post-NHRB"))

ggplot(emm_df, aes(x = period, y = response, 
                   color = EXCEPTION, group = EXCEPTION)) +
  geom_point(size = 4, position = position_dodge(0.2)) +
  geom_line(linewidth = 1.2, position = position_dodge(0.2)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), 
                width = 0.2, linewidth = 1, position = position_dodge(0.2)) +
  scale_color_manual(values = c("No Exception" = "#374e55", 
                                 "Exception" = "#00a1d5")) +
  labs(x = "Policy Period", 
       y = "Predicted Hazard",
       color = "Exception Status") +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom")


```


``` {r sensitivity}

# This plot adds demographics as a sensitivity analysis to Primary Model 1

sensitivity_data = cand_hx_list_episodes_grouping %>%
  mutate(
    sex = ifelse(GENDER == "M", "Male", "Female"),
    sex = factor(sex, levels = c("Male", "Female")),
    race = case_when(
      ETHCAT == 1 ~ "White",
      ETHCAT == 2 ~ "Black",
      ETHCAT == 4 ~ "Hispanic/Latino",
      ETHCAT == 5 ~ "Asian",
      TRUE ~ "Other"),
    race = factor(race, levels = c("White", "Black", "Hispanic/Latino", "Asian", "Other")),
    age_group = case_when(
      INIT_AGE < 1 ~ "< 1",
      INIT_AGE >= 1 & INIT_AGE < 5 ~ "1-4",
      INIT_AGE >= 5 & INIT_AGE < 12 ~ "5-11",
      INIT_AGE >= 12 ~ "> 12"),
    age_group = factor(age_group, levels = c("< 1", "1-4", "5-11", "> 12")),
    diagnosis = case_when(
      TCR_DGN > 999 & TCR_DGN < 1007 ~ "Dilated Cardiomyopathy, Non-Ischemic",
      TCR_DGN > 1049 & TCR_DGN < 1100 ~ "Restrictive Cardiomyopathy",
      TCR_DGN == 1203 | (TCR_DGN >= 1205 & TCR_DGN <= 1207) ~ "Congenital Heart Disease",
      TCR_DGN == 1201 ~ "Hypertrophic Cardiomyopathy",
      TCR_DGN >= 1100 & TCR_DGN <= 1199 ~ "Re-Heart Transplant",
      TRUE ~ "Other"),
    diagnosis = factor(diagnosis, levels = c("Dilated Cardiomyopathy, Non-Ischemic", "Restrictive Cardiomyopathy", 
                                             "Congenital Heart Disease", "Hypertrophic Cardiomyopathy", 
                                             "Re-Heart Transplant", "Other")),
    blood_type = factor(
      case_when(
        ABO %in% c("A", "A1", "A2") ~ "A",
        ABO %in% c("A1B", "A2B") ~ "AB",
        TRUE ~ ABO)),
    ecmo = ifelse(ECMO_TCR == 1, 1, 0),
    inotropes = ifelse(INOTROPES_TCR == 1, 1, 0),
    vad = ifelse(VAD_DEVICE_TY_TCR == 2 | VAD_DEVICE_TY_TCR == 3 | VAD_DEVICE_TY_TCR == 5, 1, 0),
    ventilator = ifelse(VENTILATOR_TCR == 1, 1, 0))
    

sensitivity_model_death <- coxme(Surv(start, end, death) ~ EXCEPTION + STATUS + sex + race + age_group + blood_type + diagnosis + (1 | LISTING_CTR_CODE), data = sensitivity_data)

summary(sensitivity_model_death)
exp(confint(sensitivity_model_death))


sensitivity_plot_death = plot_model(
  sensitivity_model_death,
  show.values = TRUE,
  value.offset = .3,
  value.size = 6,
  axis.labels = c("Dx: Other (Ref DCM)", "Dx: Re-Heart TX (Ref DCM)", "Dx: Hypertrophic Cardiomyopathy (Ref DCM)", "Dx: Congenital Heart Disease (Ref DCM)", "Dx: Restrictive Cardiomyopathy (Ref DCM)", "Blood Type: O (Ref A)", "Blood Type: B (Ref A)", "Blood Type: AB (Ref A)", "Age: 12 Years and Older (Ref < 1 Year)", "Age: 5-11 Years (Ref < 1 Year)", "Age: 1-4 Years (Ref < 1 Year)", "Race: Other (Ref White)", "Race: Asian (Ref White)", "Race: Hispanic/Latino (Ref White)", "Race: Black (Ref White)", "Sex: Female (Ref Male)", "Status: 1A (Ref 2)", "Status: 1B (Ref 2)", "Exception"),
  title = "",
  axis.title = "Hazard Ratio of Pre-Transplant Mortality",
  grid.breaks = c(0.01, 0.1, 1, 10, 100)) +
  theme_classic() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(size = 18),
        axis.title.x = element_text(size = 20),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.title = element_text(size = 20))



ggplot(cand_hx_list_episodes_grouping, aes(x = STATUS, fill = REC_EXCEPTION_INIT_EVER)) + 
  geom_bar() + 
  labs(x = "Status", y = "Number of Status Justifications", fill = "")





```




``` {r exceptions figure}

#THIS CODE CREATES FIGURE 3

heart_transplants = fortable1 %>% filter(REM_CD == 4)


calculations_for_heart_transplants <- heart_transplants %>% 
  mutate(EXCEPTION = ifelse(is.na(EXCEPTION), 0, EXCEPTION)) %>%
  select(WL_ID_CODE, period, EXCEPTION) %>% ungroup() %>% 
  group_by(period) %>% summarise(transplants = n(), exceptions_at_transplant = sum(EXCEPTION), na.rm = TRUE) %>%
  mutate(exceptionproportion = exceptions_at_transplant / transplants) 

calculations_for_heart_transplants <- calculations_for_heart_transplants %>% filter(period != "other")

calculations_for_heart_transplants %>% select(transplants, exceptions_at_transplant) %>% chisq.test()


exception_at_heart_transplant <- heart_transplants %>% filter(EXCEPTION == 1) %>%
  mutate(
    EXCEPTION_STATUS = case_when(
      EXCEPTION == 1 ~ "1A/1B Exception at Time of Transplant")) %>% select(WL_ID_CODE, period, EXCEPTION, EXCEPTION_STATUS, TX_DATE)

total <- heart_transplants %>% mutate(EXCEPTION_STATUS = "Total") %>% select(WL_ID_CODE, period, EXCEPTION, EXCEPTION_STATUS, TX_DATE)


  
barplotdata <- rbind(exception_at_heart_transplant, total) %>% filter(TX_DATE >= mdy("04-01-2016") & TX_DATE <= mdy("06-30-2025")) %>%
  mutate(
    status = factor(EXCEPTION_STATUS, levels = c("Total", "1A/1B Exception at Time of Transplant"))) %>%
  mutate(
    timing_of_transplants = case_when(
      TX_DATE >= mdy("04-01-2016") & TX_DATE <= mdy("06-30-2016") ~ "Apr-Jun 2016",
      TX_DATE >= mdy("07-01-2016") & TX_DATE <= mdy("09-30-2016") ~ "Jul-Sep 2016",
      TX_DATE >= mdy("10-01-2016") & TX_DATE <= mdy("12-31-2016") ~ "Oct-Dec 2016",
      TX_DATE >= mdy("01-01-2017") & TX_DATE <= mdy("03-31-2017") ~ "Jan-Mar 2017",
      TX_DATE >= mdy("04-01-2017") & TX_DATE <= mdy("06-30-2017") ~ "Apr-Jun 2017",
      TX_DATE >= mdy("07-01-2017") & TX_DATE <= mdy("09-30-2017") ~ "Jul-Sep 2017",
      TX_DATE >= mdy("10-01-2017") & TX_DATE <= mdy("12-31-2017") ~ "Oct-Dec 2017",
      TX_DATE >= mdy("01-01-2018") & TX_DATE <= mdy("03-31-2018") ~ "Jan-Mar 2018",
      TX_DATE >= mdy("04-01-2018") & TX_DATE <= mdy("06-30-2018") ~ "Apr-Jun 2018",
      TX_DATE >= mdy("07-01-2018") & TX_DATE <= mdy("09-30-2018") ~ "Jul-Sep 2018",
      TX_DATE >= mdy("10-01-2018") & TX_DATE <= mdy("12-31-2018") ~ "Oct-Dec 2018",
      TX_DATE >= mdy("01-01-2019") & TX_DATE <= mdy("03-31-2019") ~ "Jan-Mar 2019",
      TX_DATE >= mdy("04-01-2019") & TX_DATE <= mdy("06-30-2019") ~ "Apr-Jun 2019",
      TX_DATE >= mdy("07-01-2019") & TX_DATE <= mdy("09-30-2019") ~ "Jul-Sep 2019",
      TX_DATE >= mdy("10-01-2019") & TX_DATE <= mdy("12-31-2019") ~ "Oct-Dec 2019",
      TX_DATE >= mdy("01-01-2020") & TX_DATE <= mdy("03-31-2020") ~ "Jan-Mar 2020",
      TX_DATE >= mdy("04-01-2020") & TX_DATE <= mdy("06-30-2020") ~ "Apr-Jun 2020",
      TX_DATE >= mdy("07-01-2020") & TX_DATE <= mdy("09-30-2020") ~ "Jul-Sep 2020",
      TX_DATE >= mdy("10-01-2020") & TX_DATE <= mdy("12-31-2020") ~ "Oct-Dec 2020",
      TX_DATE >= mdy("01-01-2021") & TX_DATE <= mdy("03-31-2021") ~ "Jan-Mar 2021",
      TX_DATE >= mdy("04-01-2021") & TX_DATE <= mdy("04-30-2021") ~ "Apr 2021",
      TX_DATE >= mdy("05-01-2021") & TX_DATE <= mdy("05-31-2021") ~ "May 2021",
      TX_DATE >= mdy("06-01-2021") & TX_DATE <= mdy("06-30-2021") ~ "Jun 2021",
      TX_DATE >= mdy("07-01-2021") & TX_DATE <= mdy("09-30-2021") ~ "Jul-Sep 2021",
      TX_DATE >= mdy("10-01-2021") & TX_DATE <= mdy("12-31-2021") ~ "Oct-Dec 2021",
      TX_DATE >= mdy("01-01-2022") & TX_DATE <= mdy("03-31-2022") ~ "Jan-Mar 2022",
      TX_DATE >= mdy("04-01-2022") & TX_DATE <= mdy("06-30-2022") ~ "Apr-Jun 2022",
      TX_DATE >= mdy("07-01-2022") & TX_DATE <= mdy("09-30-2022") ~ "Jul-Sep 2022",
      TX_DATE >= mdy("10-01-2022") & TX_DATE <= mdy("12-31-2022") ~ "Oct-Dec 2022",
      TX_DATE >= mdy("01-01-2022") & TX_DATE <= mdy("03-31-2023") ~ "Jan-Mar 2023",
      TX_DATE >= mdy("04-01-2022") & TX_DATE <= mdy("06-30-2023") ~ "Apr-Jun 2023",
      TX_DATE >= mdy("07-01-2022") & TX_DATE <= mdy("09-30-2023") ~ "Jul-Sep 2023",
      TX_DATE >= mdy("10-01-2022") & TX_DATE <= mdy("12-31-2023") ~ "Oct-Dec 2023",
      TX_DATE >= mdy("01-01-2022") & TX_DATE <= mdy("03-31-2024") ~ "Jan-Mar 2024",
      TX_DATE >= mdy("04-01-2022") & TX_DATE <= mdy("06-30-2024") ~ "Apr-Jun 2024",
      TX_DATE >= mdy("07-01-2022") & TX_DATE <= mdy("09-30-2024") ~ "Jul-Sep 2024",
      TX_DATE >= mdy("10-01-2022") & TX_DATE <= mdy("12-31-2024") ~ "Oct-Dec 2024",
      TX_DATE >= mdy("01-01-2022") & TX_DATE <= mdy("03-31-2025") ~ "Jan-Mar 2025",
      TX_DATE >= mdy("04-01-2022") & TX_DATE <= mdy("06-30-2025") ~ "Apr-Jun 2025"),
    timing_of_transplants = factor(timing_of_transplants, levels = c("Apr-Jun 2016", "Jul-Sep 2016", "Oct-Dec 2016", "Jan-Mar 2017", "Apr-Jun 2017", "Jul-Sep 2017", "Oct-Dec 2017", "Jan-Mar 2018", "Apr-Jun 2018", "Jul-Sep 2018", "Oct-Dec 2018", "Jan-Mar 2019", "Apr-Jun 2019", "Jul-Sep 2019", "Oct-Dec 2019", "Jan-Mar 2020", "Apr-Jun 2020", "Jul-Sep 2020", "Oct-Dec 2020", "Jan-Mar 2021", "Apr 2021", "May 2021", "Jun 2021", "Jul-Sep 2021", "Oct-Dec 2021", "Jan-Mar 2022", "Apr-Jun 2022", "Jul-Sep 2022", "Oct-Dec 2022", "Jan-Mar 2023", "Apr-Jun 2023", "Jul-Sep 2023", "Oct-Dec 2023", "Jan-Mar 2024", "Apr-Jun 2024", "Jul-Sep 2024", "Oct-Dec 2024", "Jan-Mar 2025", "Apr-Jun 2025")))



by_month <- barplotdata %>%
  group_by(timing_of_transplants) %>%
  count(status) %>%
  mutate(total_per_month = sum(n)) %>%
  ungroup() %>%
  mutate(percentage_per_month = 100*n/total_per_month) 
# policy_switch <- which(levels(by_month$month) == "Jun 2021")
# pre_policy_start <- which(levels(by_month$month) == "Jul 2017")
# pre_policy_end <- which(levels(by_month$month) == "Feb 2021")
# post_policy_start <- which(levels(by_month$month) == "Jul 2021")
# post_policy_end <- which(levels(by_month$month) == "Feb 2025")


exceptions_at_transplant_barplot <- ggplot(by_month, aes(x = timing_of_transplants, y = percentage_per_month, fill = status, group = status)) +
  geom_col(alpha = 0.75, color = "NA") +
  geom_vline(aes(xintercept = "Jun 2021", linetype = "NHRB Implementation Date")) + 
  #scale_color_custom(name = "Exception Status at Transplant", palette = "simple") +
  labs(
    x = "",
    y = "% Exceptions at Transplant",
    linetype = "",
    fill = "status") +
  scale_y_continuous(limits = c(0, 30), breaks = seq(0, 300, by = 10)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 16),
        axis.title.x = element_text(margin = margin(t = 15, r = 0, b = 0, l = 0), size = 20),
        axis.text.y = element_text(size = 18),
        axis.title.y = element_text(size = 18),
        legend.position = "bottom",
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.margin = margin(t=0, r=0, b=0, l=0, unit = "mm"),
        legend.direction = "vertical",
        legend.title.align = 0,
        panel.background = element_rect(fill = "grey99"),
        plot.background = element_rect(fill = "white"),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line = element_line(linewidth = 0.5, linetype = "solid", colour = "black")
  ) +
  scale_linetype_manual(values = c("dashed", "dotted", "solid")) +
  scale_fill_manual(name = "", values = c("#b24745", "white"), breaks = c("Status 1A/1B Exception")) + 
  guides(fill = guide_legend(nrow = 2)) +
  annotate("text", x = "Apr-Jun 2019", y = 28, label= "Pre-NHRB Cohort", size = 16/.pt) +
  annotate("text", x = "Apr-Jun 2023", y = 28, label= "Post-NHRB Cohort", size = 16/.pt) +
  annotate("rect",
           xmin = "Jul-Sep 2017",           
           xmax = "Jan-Mar 2021",
           ymin = 0, 
           ymax = 30,  
           alpha = 0.15) +
  annotate("rect",
           xmin = "Jul-Sep 2021",            
           xmax = "Jan-Mar 2025",            
           ymin = 0, 
           ymax = 30, 
           alpha = 0.15) 



```




``` {r auc}
#THE FOLLOWING CODE WAS REMOVED FROM MANUSCRIPT DURING REVISION PROCESS

# require(rsample)
# require(risksetROC)
# 
# data_for_cindex = cand_hx_list_episodes_grouping %>% dplyr::select(WL_ID_CODE, INIT_AGE, TCR_DGN, start, end, death, EXCEPTION, STATUS) %>%
#   group_by(WL_ID_CODE) %>% arrange(WL_ID_CODE, start) %>%
#   mutate(
#     status_without_exception = case_when(
#       STATUS == "1B" & EXCEPTION == 1 ~ "2",
#       STATUS == "1A" & EXCEPTION == 1 ~ "1B",
#       TRUE ~ STATUS),
#     new_status_normal = case_when(
#       STATUS == "1A" ~ 1,
#       STATUS == "1B" ~ 2,
#       STATUS == "2" ~ 3),
#     new_status_hypothetical = case_when(
#       status_without_exception == "1A" ~ 1,
#       status_without_exception == "1B" ~ 2,
#       status_without_exception == "2" ~ 3),
#     death_6weeks = ifelse(death == 1 & end <= 42, 1, 0),
#     death_6weeks = ifelse(any(death_6weeks == 1), 1, 0)
#     )
# 
# auc_graph_data = data_for_cindex %>% slice(1) %>%
#   mutate(
#     auc_status_with_exception = case_when(
#       STATUS == "1A" ~ 1,
#       STATUS == "1B" ~ 2,
#       STATUS == "2" ~ 3),
#     auc_status_without_exception = case_when(
#       status_without_exception == "1A" ~ 1,
#       status_without_exception == "1B" ~ 2,
#       status_without_exception == "2" ~ 3),
#     auc_status_with_exception = factor(auc_status_with_exception, ordered = TRUE, levels = c(1, 2, 3), labels = c("Status 1A", "Status 1B", "Status 2")),
#     auc_status_without_exception = factor(auc_status_without_exception, ordered = TRUE, levels = c(1, 2, 3), labels = c("Status 1A", "Status 1B", "Status 2")),
#     nope = factor(STATUS, ordered = TRUE, levels = c("1A", "1B", "2")))
# 
# roc_obj <- pROC::roc(auc_graph_data$death_6weeks, auc_graph_data$nope, direction = ">")
# pROC::ggroc(roc_obj)
# 
# par(xaxs='i')
# par(pty = "s")
# par(cex.axis = 1.2, cex.lab = 1.2) 
# # First ROC curve (plots the graph and the first AUC label)
# pROC::roc(data = auc_graph_data, response = death_6weeks, predictor = nope, direction='>',
#           plot=T, col="#374e55", print.auc=T, ci=T, ci.type = 'no',
#           lwd=3, quiet=T, 
#           #print.thres = c("Status 1A", "Status 1B", "Status 2"), 
#           #print.thres = c("1A", "1B", "2"),
#           print.thres = c("no"),
#           print.thres.cex = 1.1, 
#           print.thres.pattern= "Status%2.f",
#           print.auc.cex = 1.2, 
#           legacy.axes=T,
#           print.auc.y = 0.4,
#           identity = TRUE, # Add the identity line (diagonal)
#           lty.identity = 2, # Line type for the identity line (2 for dotted)
#           col.identity = "darkgrey")
# 
# # Second ROC curve (adds to the graph and prints the second AUC label at a new y-coordinate)
# pROC::roc(data = auc_graph_data, response = death_6weeks, predictor = auc_status_without_exception, direction='>',
#           plot=T, col="#df8f44", print.auc=T, ci=T, ci.type = 'no',
#           lwd=3, quiet=T, 
#           print.thres = c("no"), 
#           print.thres.cex = 1.1, 
#           print.thres.pattern= "Status%2.f",
#           print.auc.cex = 1.2, 
#           legacy.axes=T,
#           add = T,
#           print.auc.y = 0.35) # Adjust this value (e.g., 0.35, 0.45) to move the label
# 
# #text(x=0.05, y=1.02, labels='')
# legend('bottomright', xpd = T, 
#        legend = c('With Status Exceptions', 'No Status Exceptions'),
#        col = c("#374e55", "#df8f44"), lwd=2.0, cex=1.0)
# 
# 
# 
# current = pROC::roc(data = auc_graph_data, response = death_6weeks, predictor = nope, direction='>',
#           plot=T, col="#374e55", print.auc=T, ci=T, ci.type = 'no',
#           lwd=3, quiet=T, 
#           #print.thres = c("Status 1A", "Status 1B", "Status 2"), 
#           #print.thres = c("1A", "1B", "2"),
#           print.thres = c("no"),
#           print.thres.cex = 1.1, 
#           print.thres.pattern= "Status%2.f",
#           print.auc.cex = 1.2, 
#           legacy.axes=T,
#           print.auc.y = 0.4,
#           identity = TRUE, # Add the identity line (diagonal)
#           lty.identity = 2, # Line type for the identity line (2 for dotted)
#           col.identity = "darkgrey")
# 
# hypothetical = pROC::roc(data = auc_graph_data, response = death_6weeks, 
#                          predictor = auc_status_without_exception, direction='>', 
#                          plot=T, col="#df8f44", print.auc=T, ci=T, ci.type = 'no',
#                          lwd=3, quiet=T, print.thres = c("no"), print.thres.cex = 1.1, print.thres.pattern= "Status%2.f",
#                          print.auc.cex = 1.2, legacy.axes=T, print.auc.y = 0.35) 
# 
# 
# currentvalues = coords(current, c(1, 2, 3))
# hypotheticalvalues = coords(hypothetical, c(1, 2, 3))

```


``` {r c index}

data_for_cindex = cand_hx_list_episodes_grouping %>% 
  dplyr::select(WL_ID_CODE, INIT_AGE, TCR_DGN, start, end, death, EXCEPTION, STATUS) %>%
  group_by(WL_ID_CODE) %>% arrange(WL_ID_CODE, start) %>%
  mutate(
    status_without_exception = case_when(
      STATUS == "1B" & EXCEPTION == 1 ~ "2",
      STATUS == "1A" & EXCEPTION == 1 ~ "1B",
      TRUE ~ STATUS),
    new_status_normal = case_when(
      STATUS == "1A" ~ 1,
      STATUS == "1B" ~ 2,
      STATUS == "2" ~ 3),
    new_status_hypothetical = case_when(
      status_without_exception == "1A" ~ 1,
      status_without_exception == "1B" ~ 2,
      status_without_exception == "2" ~ 3),
    death_6weeks = ifelse(death == 1 & end <= 42, 1, 0),
    death_6weeks = ifelse(any(death_6weeks == 1), 1, 0)
    )

normalallocation <- coxph(Surv(start, end, death) ~ new_status_normal, data = data_for_cindex)
data_for_cindex$normal_predict <- predict(normalallocation, data_for_cindex, type = "lp")
get_normal_c <- function(data) {
  r <- risksetAUC(
    Stime = data$end,
    entry = data$start,
    status = data$death,
    marker = data$normal_predict,
    method = "Cox",
    tmax = 365,
    plot = F)
  return(r$Cindex)
}


timeseriesdata_short1 <- data_for_cindex[ ,c("WL_ID_CODE", "start", "end", "death", "normal_predict")]
timeseriesdata_nest1 <- timeseriesdata_short1 %>% nest(data = -WL_ID_CODE)

set.seed(200)
get_normal_c(data_for_cindex)

n_iterations <- 1000
bs <- rsample::bootstraps(timeseriesdata_nest1, times = n_iterations)
auc_normal <- vector(length = n_iterations)

for (i in 1:n_iterations) {
  normal_c <- as_tibble(bs$splits[[i]]) %>% unnest(cols = c("data")) %>% as.data.frame()
  auc_normal[i] <- get_normal_c(normal_c)
}


quantile(auc_normal, probs = c(0.025, 0.975))


hypotheticalallocation <- coxph(Surv(start, end, death) ~ new_status_hypothetical, data = data_for_cindex)
data_for_cindex$hypothetical_predict <- predict(hypotheticalallocation, data_for_cindex, type = "lp")
get_hypothetical_c <- function(data) {
  r <- risksetAUC(
    Stime = data$end,
    entry = data$start,
    status = data$death,
    marker = data$hypothetical_predict,
    method = "Cox",
    tmax = 365,
    plot = F)
  return(r$Cindex)
}

timeseriesdata_short2 <- data_for_cindex[ ,c("WL_ID_CODE", "start", "end", "death", "hypothetical_predict")]
timeseriesdata_nest2 <- timeseriesdata_short2 %>% nest(data = -WL_ID_CODE)

set.seed(200)
get_hypothetical_c(data_for_cindex)


n_iterations <- 1000
bs1 <- rsample::bootstraps(timeseriesdata_nest2, times = n_iterations)
auc_hypothetical <- vector(length = n_iterations)

for (i in 1:n_iterations) {
  hypothetical_c <- as_tibble(bs1$splits[[i]]) %>% unnest(cols = c("data")) %>% as.data.frame()
  auc_hypothetical[i] <- get_hypothetical_c(hypothetical_c)
}


quantile(auc_hypothetical, probs = c(0.025, 0.975))

library(compareC)

compareC(data_for_cindex$end, data_for_cindex$death, data_for_cindex$new_status_normal, data_for_cindex$new_status_hypothetical)


#The FOLLOWING CODE WAS REMOVED FROM MANUSCRIPT DURING REVISION

# c_boxplot = boxplot(auc_normal, auc_hypothetical, names = c("With Exceptions", "Without Exceptions"), col = c("lightblue", "lightgreen"))
# 
# 
# data_df <- data.frame(
#   value = c(auc_normal, auc_hypothetical),
#   group = factor(c(rep("With Exceptions", length(auc_normal)), rep("Without Exceptions", length(auc_hypothetical)))))
#     
# c_boxplot = ggplot(data_df, aes(x = group, y = value, fill = group)) +
#   geom_boxplot() +
#   labs(title = "",
#        x = "Concordance Indices",
#        y = "Value") +
#   theme_classic() +
#   scale_fill_manual(values = c("With Exceptions" = "#374e55", "Without Exceptions" = "#df8f44")) +
#   ylim(0.65, 0.75) +
#   theme(text = element_text(size = 20),
#         axis.text.x = element_text(size = 18),
#         axis.title.x = element_text(size = 20),
#         axis.text.y = element_text(size = 18),
#         axis.title.y = element_text(size = 20),
#         legend.position = "none")
#     
# # Find max y-value to determine the annotation's vertical position
# max_y <- max(data_df$value)
# y_pos <- max_y + 0.005 # Position the bracket slightly above the highest point
# 
# # Annotation data frame for geom_segment and geom_text
# signif_annot <- data.frame(
#   x_start = 1, # x-position of "With Exceptions"
#   x_end = 2,   # x-position of "Without Exceptions"
#   y_bar = y_pos,
#   y_text = y_pos + 0.002,
#   label = "***"
# )
# 
# # Create the boxplot with the manually added significance indicator
# c_boxplot <- ggplot(data_df, aes(x = group, y = value, fill = group)) +
#   geom_boxplot() +
#   labs(title = "",
#        x = "Concordance Indices",
#        y = "Value") +
#   theme_classic() +
#   scale_fill_manual(values = c("With Exceptions" = "#374e55", "Without Exceptions" = "#df8f44")) +
#   ylim(0.65, 0.75) +
#   theme(text = element_text(size = 20),
#         axis.text.x = element_text(size = 18),
#         axis.title.x = element_text(size = 20),
#         axis.text.y = element_text(size = 18),
#         axis.title.y = element_text(size = 20),
#         legend.position = "none") +
#   # Add horizontal segment for the bracket
#   geom_segment(data = signif_annot, aes(x = x_start, xend = x_end, y = y_bar, yend = y_bar), inherit.aes = FALSE) +
#   # Add vertical tips to the bracket
#   geom_segment(data = signif_annot, aes(x = x_start, xend = x_start, y = y_bar, yend = y_bar - 0.001), inherit.aes = FALSE) +
#   geom_segment(data = signif_annot, aes(x = x_end, xend = x_end, y = y_bar, yend = y_bar - 0.001), inherit.aes = FALSE) +
#   # Add the significance text
#   geom_text(data = signif_annot, aes(x = (x_start + x_end) / 2, y = y_text, label = label), size = 7, inherit.aes = FALSE)

```


``` {r time-dependent auc}

#THIS CREATES FIGURE 5

get_time_dependent_auc <- function(data, marker_col) {
  roc_result <- risksetAUC(
    Stime = data$end,
    entry = data$start,
    status = data$death,
    marker = data[[marker_col]],
    method = "Cox",
    tmax = 365,
    plot = FALSE
  )
  
  tibble(
    time = roc_result$utimes,
    auc = roc_result$AUC,
    c_index = roc_result$Cindex
  )
}

# ============================================================================
# SECTION 3: Calculate Point Estimates
# ============================================================================

set.seed(200)
auc_normal_point <- get_time_dependent_auc(data_for_cindex, "normal_predict")
auc_hypothetical_point <- get_time_dependent_auc(data_for_cindex, "hypothetical_predict")

cat("Normal allocation C-index:", round(auc_normal_point$c_index[1], 3), "\n")
cat("Hypothetical allocation C-index:", round(auc_hypothetical_point$c_index[1], 3), "\n\n")

# ============================================================================
# SECTION 4: Bootstrap
# ============================================================================

# Prepare nested data
timeseriesdata_nest <- data_for_cindex %>%
  select(WL_ID_CODE, start, end, death, normal_predict, hypothetical_predict) %>%
  nest(data = -WL_ID_CODE)

set.seed(200)
n_iterations <- 1000

cat("Running", n_iterations, "bootstrap iterations...\n\n")

# Create bootstrap samples
bs <- bootstraps(timeseriesdata_nest, times = n_iterations)

# Bootstrap for Normal allocation
cat("Bootstrap for Normal allocation...\n")
auc_normal_bootstrap <- map(1:n_iterations, function(i) {
  if (i %% 100 == 0) cat("  Iteration", i, "/", n_iterations, "\n")
  
  boot_data <- as_tibble(bs$splits[[i]]) %>% 
    unnest(cols = c(data))
  
  get_time_dependent_auc(boot_data, "normal_predict") %>%
    mutate(iteration = i)
})

auc_normal_bootstrap_df <- bind_rows(auc_normal_bootstrap)

# Bootstrap for Hypothetical allocation
cat("\nBootstrap for Hypothetical allocation...\n")
auc_hypothetical_bootstrap <- map(1:n_iterations, function(i) {
  if (i %% 100 == 0) cat("  Iteration", i, "/", n_iterations, "\n")
  
  boot_data <- as_tibble(bs$splits[[i]]) %>% 
    unnest(cols = c(data))
  
  get_time_dependent_auc(boot_data, "hypothetical_predict") %>%
    mutate(iteration = i)
})

auc_hypothetical_bootstrap_df <- bind_rows(auc_hypothetical_bootstrap)

cat("\nBootstrap complete!\n\n")

# ============================================================================
# SECTION 5: Interpolate to Fixed Time Grid (NEW SECTION - GOES HERE)
# ============================================================================

cat("Interpolating to fixed time grid...\n")

# Define fixed time grid
time_grid <- seq(0, 365, by = 5)  # Every 5 days

# Function to interpolate one bootstrap iteration
interpolate_one_bootstrap <- function(df) {
  # Handle edge cases
  if (nrow(df) < 2) {
    return(tibble(time = time_grid, auc = NA_real_))
  }
  
  tryCatch({
    interpolated_auc <- approx(
      x = df$time,
      y = df$auc,
      xout = time_grid,
      method = "linear",
      rule = 2
    )$y
    
    tibble(time = time_grid, auc = interpolated_auc)
  }, error = function(e) {
    # If interpolation fails, return NAs
    tibble(time = time_grid, auc = NA_real_)
  })
}

# Nest by iteration and interpolate
# Normal allocation
auc_normal_interpolated <- auc_normal_bootstrap_df %>%
  nest(data = c(time, auc, c_index)) %>%
  mutate(interpolated = map(data, interpolate_one_bootstrap)) %>%
  dplyr::select(iteration, interpolated) %>%
  unnest(interpolated)

# Check for any NAs
n_na_normal <- sum(is.na(auc_normal_interpolated$auc))
if (n_na_normal > 0) {
  cat("Warning:", n_na_normal, "NA values in normal allocation interpolation\n")
}

# Hypothetical allocation
auc_hypothetical_interpolated <- auc_hypothetical_bootstrap_df %>%
  nest(data = c(time, auc, c_index)) %>%
  mutate(interpolated = map(data, interpolate_one_bootstrap)) %>%
  dplyr::select(iteration, interpolated) %>%
  unnest(interpolated)

# Check for any NAs
n_na_hypo <- sum(is.na(auc_hypothetical_interpolated$auc))
if (n_na_hypo > 0) {
  cat("Warning:", n_na_hypo, "NA values in hypothetical allocation interpolation\n")
}

cat("Interpolation complete!\n\n")

# ============================================================================
# SECTION 6: Calculate Confidence Intervals at Fixed Time Points
# ============================================================================

# Normal allocation CIs
auc_normal_ci_fixed <- auc_normal_interpolated %>%
  group_by(time) %>%
  summarise(
    mean_auc = mean(auc, na.rm = TRUE),
    ci_lower = quantile(auc, 0.025, na.rm = TRUE),
    ci_upper = quantile(auc, 0.975, na.rm = TRUE),
    n_samples = sum(!is.na(auc)),  # Count non-NA samples
    .groups = "drop"
  )

# Hypothetical allocation CIs
auc_hypothetical_ci_fixed <- auc_hypothetical_interpolated %>%
  group_by(time) %>%
  summarise(
    mean_auc = mean(auc, na.rm = TRUE),
    ci_lower = quantile(auc, 0.025, na.rm = TRUE),
    ci_upper = quantile(auc, 0.975, na.rm = TRUE),
    n_samples = sum(!is.na(auc)),
    .groups = "drop"
  )

# Interpolate point estimates to same grid
auc_normal_point_interpolated <- tibble(
  time = time_grid,
  point_estimate = approx(
    auc_normal_point$time, 
    auc_normal_point$auc, 
    xout = time_grid, 
    rule = 2
  )$y
)

auc_hypothetical_point_interpolated <- tibble(
  time = time_grid,
  point_estimate = approx(
    auc_hypothetical_point$time, 
    auc_hypothetical_point$auc, 
    xout = time_grid, 
    rule = 2
  )$y
)

# Combine with CIs
auc_normal_ci_final <- auc_normal_ci_fixed %>%
  left_join(auc_normal_point_interpolated, by = "time") %>%
  mutate(system = "Normal Allocation")

auc_hypothetical_ci_final <- auc_hypothetical_ci_fixed %>%
  left_join(auc_hypothetical_point_interpolated, by = "time") %>%
  mutate(system = "Hypothetical Allocation")

# Combine both systems
auc_combined_ci <- bind_rows(auc_normal_ci_final, auc_hypothetical_ci_final)

# Verify
cat("=== Verification ===\n")
cat("Normal allocation samples per time point - min:", 
    min(auc_normal_ci_fixed$n_samples), 
    "max:", max(auc_normal_ci_fixed$n_samples), "\n")
cat("Hypothetical allocation samples per time point - min:", 
    min(auc_hypothetical_ci_fixed$n_samples), 
    "max:", max(auc_hypothetical_ci_fixed$n_samples), "\n")
cat("Number of time points:", length(time_grid), "\n\n")

# ============================================================================
# SECTION 7: Plot Time-Dependent AUC with Confidence Bands
# ============================================================================

auc_plot <- ggplot(auc_combined_ci, 
                   aes(x = time, y = point_estimate, 
                       color = system, fill = system)) +
  
  #geom_hline(yintercept = 0.5, linetype = "dashed", 
  #           color = "gray50", linewidth = 0.5) +
  
  geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper), 
              alpha = 0.2, color = NA) +
  
  geom_line(linewidth = 1.2) +
  
  scale_color_manual(
    values = c(
      "Normal Allocation" = "#DF8F44",
      "Hypothetical Allocation" = "#374E55"
    ),
    labels = c(
      "Normal Allocation" = "Current 3-Status System",
      "Hypothetical Allocation" = "Hypothetical Allocation\nwithout Exceptions"
    ),
    name = ""
  ) +
  
  scale_fill_manual(
    values = c(
      "Normal Allocation" = "#DF8F44",
      "Hypothetical Allocation" = "#374E55"
    ),
    labels = c(
      "Normal Allocation" = "Current 3-Status System",
      "Hypothetical Allocation" = "Hypothetical Allocation\nwithout Exceptions"
    ),
    name = ""
  ) +
  
  scale_x_continuous(
    breaks = seq(0, 365, 60),
    limits = c(0, 365)
  ) +
  
  scale_y_continuous(
    limits = c(0.6, 0.85),
    breaks = seq(0.6, 0.85, 0.05)
  ) +
  
  labs(
    x = "Days after Initial Listing",
    y = "Time-Dependent AUC",
    #title = "Discrimination Performance Over Time",
    #subtitle = "Shaded bands represent 95% bootstrap confidence intervals",
    #caption = "Dashed line represents AUC = 0.5 (no discrimination)"
  ) +
  
  theme_classic(base_size = 16) +
  theme(
    legend.position.inside = c(0.8, 0.2),  # CHANGED: was legend.position
    legend.text = element_text(size = 16),
    #legend.background = element_rect(fill = "white", color = "black", linewidth = 0.3),
    plot.title = element_text(face = "bold", size = 16, hjust = 0),
    plot.subtitle = element_text(size = 16, hjust = 0),
    plot.caption = element_text(size = 16, hjust = 0, color = "gray40"),
    axis.title = element_text(face = "bold", size = 16),
    axis.text.x = element_text(size = 16),  # INCREASE X-AXIS NUMBERS
    axis.text.y = element_text(size = 16),  # INCREASE Y-AXIS NUMBERS
    panel.grid.major.y = element_line(color = "gray90", linewidth = 0.3)
  )

print(auc_plot)

```

